local BattleDataStatisticsPropertyFieldDef = {
    PLAYERID            = "PlayerId",
    LOGINOUT            = "LoginOut",
    KILL                = "Kill",
    DEATH               = "Death",
    SHIPKILLSHIP        = "ShipKillShip",
    HUMANKILLHUMAN      = "HumanKillHuman",
    SHIPKILLHUMAN       = "ShipKillHuman",
    APPLYDAMAGETOSHIP   = "ApplyDamageToShip",
    APPLYDAMAGETOHUMAN  = "ApplyDamageToHuman",
    APPLYCURETOSHIP     = "ApplyCureToShip",
    APPLYCURETOHUMAN    = "ApplyCureToHuman",
    -- APPLIEDDAMAGE       = "AppliedDamage",
    SHIPAPPLIEDDAMAGE   = "ShipAppliedDamage",
    HUMANAPPLIEDDAMAGE  = "HumanAppliedDamage",
    SURVIVALTIME        = "SurvivalTime",
    GAMETIME            = "GameTime",
    SHIPMOVEDISTANCE    = "ShipMoveDistance",
    HUMANMOVEDISTANCE   = "HumanMoveDistance",
    SHIPLAUNCHCOUNT     = "ShipLaunchCount",
    SHIPHITCOUNT        = "ShipHitCount",
    HUMANLAUNCHCOUNT    = "HumanLaunchCount",
    HUMANHITCOUNT       = "HumanHitCount",
    HITSHIPCORECOUNT    = "HitShipCoreCount",
    HITHUMANCORECOUNT   = "HitHumanCoreCount",
    SAVETEAMATECOUNT    = "SaveTeamateCount",
    RESCUINGCOUNT       = "RescuingCount",
    MELEEATTACKCOUNT    = "MeleeAttackCount",
    GAMEOVERUSESHIP     = "GameOverUseShip",
    GRADE               = "Grade",
    PLAYERRANK          = "PlayerRank",
    GRADESCORE          = "GradeScore",
    BATTLESCORE         = "BattleScore",
    SURVIVALSCORE       = "SurvivalScore",
    KILLSCORE           = "KillScore",
    DIMENSIIONALSURVIVAL= "DimensionalSurvival",
    DIMENSIIONALDAMAGE  = "DimensionalDamage",
    DIMENSIIONALKILL    = "DimensionalKill",
    DIMENSIIONALASSIST  = "DimensionalAssist",
    DIMENSIIONALITEM    = "DimensionalItem",
    
    PAIDREVIVE          = "PaidRevive",
    POISONCIRCLELEAVETIME= "PoisonCircleLeaveTime",
    POISONCIRCLETIME    = "PoisonCircleTime",
    ASSISTCOUNT         = "AssistCount",
    KILLNPC             = "KillNpc",
-- define combat propertry
    DUNGEONBEGINTIME    = "DungeonBeginTime",
    DUNGEONELAPSEDTIME  = "DungeonElapsedTime",
    FIRSTAIRDROP        = "FirstAirDrop",
    TOTALGRADE          = "TOTALGRADE",
    PLAYERCOUNT         = "PLAYERCOUNT",

-- define team property
    TEAMID              = "TeamId",
    TEAMRANK            = "TeamRank",
}

return BattleDataStatisticsPropertyFieldDef