local SaveGameDef = {}

SaveGameDef.CHOSEN_SERVER_ID = "CHOSEN_SERVER_ID"
SaveGameDef.CONTACT_LIST = "CONTACT_LIST"
SaveGameDef.FRIEND_CHAT_MESSAGES = "FRIEND_CHAT_MESSAGES"
SaveGameDef.BATTLE_ARENA_POINT = "BATTLE_ARENA_POINT"
SaveGameDef.USER_NAME = "USER_NAME"
SaveGameDef.LOGIN_ANNOUNCEMENT = "LOGIN_ANNOUNCEMENT"
SaveGameDef.LOGIN_ANNOUNCEMENT_ETAG = "LOGIN_ANNOUNCEMENT_ETAG"

SaveGameDef.LAST_SHIP_ID = "LAST_SHIP_ID"
SaveGameDef.SELECT_DEFAULT_PLAYER = "SELECT_DEFAULT_PLAYER"
SaveGameDef.SELECT_CREATE_PLAYER = "SELECT_CREATE_PLAYER"

SaveGameDef.DISABLE_ATMOSPHERE_NPC = "DISABLE_ATMOSPHERE_NPC"
SaveGameDef.ENABLE_ATMOSPHERE_MOVE_ON_ABORT = "ENABLE_ATMOSPHERE_MOVE_ON_ABORT"

SaveGameDef.DEVICE_PERFORMANCE_LEVEL_CHECKED = "DEVICE_PERFORMANCE_LEVEL_CHECKED"

SaveGameDef.DEVICEID = "UPDATEDEVICEID"

SaveGameDef.LAND_GATHER = "LAND_GATHER"

SaveGameDef.NUM_DETAILED_BATTLE_RECORD = "NUM_DETAILED_BATTLE_RECORD"
SaveGameDef.DETAILED_BATTLE_RECORD_DATA = "DETAILED_BATTLE_RECORD_DATA"

SaveGameDef.DEBUG_PANEL_LAST_INDEX = "DEBUG_PANEL_LAST_INDEX"

SaveGameDef.SETTING_MUSIC = "SETTING_MUSIC"
SaveGameDef.SETTING_SOUND = "SETTING_SOUND"
SaveGameDef.SETTING_HEADINFO = "SETTING_HEADINFO"
SaveGameDef.SETTING_COMMONINPUT = "CAMERA_COMMON_INPUT_SCALE"
SaveGameDef.SETTING_AIMINPUT = "CAMERA_AIM_INPUT_SCALE"

SaveGameDef.SETTING_PAINTINGQUALITY = "SETTING_PAINTINGQUALITY"
SaveGameDef.SETTING_SHADOWQUALITY = "SETTING_SHADOWQUALITY"
SaveGameDef.SETTING_EFFECTQUALITY = "SETTING_EFFECTQUALITY"
SaveGameDef.SETTING_FOLIAGEQUALITY= "SETTING_FOLIAGEQUALITY"
SaveGameDef.SETTING_DEPTHOFFIELD = "SETTING_DEPTHOFFIELD"
SaveGameDef.SETTING_BLOOM = "SETTING_BLOOM"
SaveGameDef.SETTING_VIEWDISTANCEQUALITY = "SETTING_VIEWDISTANCEQUALITY"

SaveGameDef.FRIEND_TEAM = "FRIEND_TEAM"
SaveGameDef.FRIEND_CHAT = "FRIEND_CHAT"

SaveGameDef.GUIDE_DATA = "GUIDE_DATA"

SaveGameDef.HOMELAND_SWITCH_FLAG = "HOMELAND_SWITCH_FLAG"
SaveGameDef.RECENTLY_TEAM = "RECENTLY_TEAM"
SaveGameDef.DUNGEON_APPLY_FRIENDS = "DUNGEON_APPLY_FRIENDS"
SaveGameDef.DUNGEON_START_TIME = "DUNGEON_START_TIME"

SaveGameDef.UI_CAPTAIN_FASHION_ALL_HINT          = "UI_CAPTAIN_FASHION_ALL_HINT"
SaveGameDef.UI_CAPTAIN_FASHION_HAT_HINT          = "UI_CAPTAIN_FASHION_HAT_HINT"
SaveGameDef.UI_CAPTAIN_FASHION_MASK_HINT         = "UI_CAPTAIN_FASHION_MASK_HINT"
SaveGameDef.UI_CAPTAIN_FASHION_UPPER_BODY_HINT   = "UI_CAPTAIN_FASHION_UPPER_BODY_HINT"
SaveGameDef.UI_CAPTAIN_FASHION_LOWER_BODY_HINT   = "UI_CAPTAIN_FASHION_LOWER_BODY_HINT"
SaveGameDef.UI_CAPTAIN_FASHION_SHOW_HINT         = "UI_CAPTAIN_FASHION_SHOW_HINT"
SaveGameDef.UI_CAPTAIN_DECORATION_ALL_HINT       = "UI_CAPTAIN_DECORATION_ALL_HINT"
SaveGameDef.FASHION_NEW_ITEMS                    = "FASHION_NEW_ITEMS"
SaveGameDef.WAEPON_FASHION_NEW_ITEMS             = "WAEPON_FASHION_NEW_ITEMS"
SaveGameDef.DECORATION_NEW_ITEMS                 = "DECORATION_NEW_ITEMS"
SaveGameDef.NEW_ITEMS_IN_BACKPACK                = "NEW_ITEMS_IN_BACKPACK"
SaveGameDef.HAVE_NEW_ITEMS_IN_BACKPACK           = "HAVE_NEW_ITEMS_IN_BACKPACK"

SaveGameDef.NEW_SHIP_ITEMS                       = "NEW_SHIP_ITEMS"

SaveGameDef.EGSDK_SHOW_SCORE_DIALOG              = "EGSDK_SHOW_SCORE_DIALOG"
SaveGameDef.EGSDK_SHOW_BIND_DIALOG               = "EGSDK_SHOW_BIND_DIALOG"

SaveGameDef.UI_FIRST_PURCHASE = "UI_FIRST_PURCHASE"
SaveGameDef.BATTLE_STAR_SCHEDULE = "BATTLE_STAR_SCHEDULE"

SaveGameDef.UI_MAP_LAND_ID  = "UI_MAP_LAND_ID"

SaveGameDef.SURVEY_STATUS   = "SURVEY_STATUS"

SaveGameDef.VOICE_DEFAULT_MIC_OPTION         = "VOICE_DEFAULT_MIC_OPTION"
SaveGameDef.VOICE_DEFAULT_MIC_PRESS_OPTION   = "VOICE_DEFAULT_MIC_PRESS_OPTION"
SaveGameDef.VOICE_DEFAULT_SPEAKER_OPTION     = "VOICE_DEFAULT_SPEAKER_OPTION"

SaveGameDef.GUIDE_REPEAT_MAX_TIME_PREFIX     = "GUIDE_REPEAT_MAX_TIME_"

SaveGameDef.GUIDE_SINGLE_BE_NEW_PLAYER       = "GUIDE_SINGLE_BE_NEW_PLAYER"
SaveGameDef.GUIDE_SINGLE_BE_COMPLETE         = "GUIDE_SINGLE_BE_COMPLETE"

SaveGameDef.NEXT_NOOB_LOGIN       = "NEXT_NOOB_LOGIN"
SaveGameDef.TODAY_BATTLE_COUNT    = "TODAY_BATTLE_COUNT"

SaveGameDef.NEW_RESERVATION       = "NEW_RESERVATION"

SaveGameDef.SENDCOIN_IDS          = "SENDCOIN_IDS"

SaveGameDef.FILL_QUESTION         = "FILL_QUESTION"

SaveGameDef.ENABLE_DLC            = "ENABLE_DLC"

SaveGameDef.LOBBY_CAPTAIN_WEAPON_MODE         = "LOBBY_CAPTAIN_WEAPON_MODE"

return SaveGameDef