-- 此处填写DS和Client上都需要ignore的日志匹配规则，支持正则
local LogReportWhiteList = {
    'Using Slow CreateWidget path because this class could not be templated',
    'Stalled gamethread waiting for particles',
    'OnPawnLeaveArea failed, gameobject is invalid',
    "SL Entered Init HW",
    "OpenSLES Initializing HW",
    "OpenSLES Initialized",
    "OpenSLAudioDevice: Allocated 12 sources",
    "[Client]: pLocation",
    "Long net serialize",
    "HumanCells: MemorySize:",
    "AverageDataInUsedCell",
    "MaxDataCount",
    "AverageDataInUsedCell",
    "Player: localhost",
    "ManagerTotalMemorySize",
    "MapWidth",
    "ShipCells",
    "DataAroundPlayer",
    "ms for audio",
    "CreateSavedMove: Hit limit",
    "Failed to load Shared Shader Library",
    "FontCache flush requested",
    "FShaderPipelineCache completed",
    "ClientAdjustPosition_Implementation",
    "request has been successfully processed",
    "Response Header Content-Length:",
    "Response Header Content-Type: application/json",
    "Response Header X-Requestid",
    "Response Header Date:",
    "Login failed: InternalError javax.net.ssl.SSLException: Read timed out",
    "Login failed: InternalError java.net.SocketTimeoutException: connect timed out",
    "Task graph took",
    "ConvertQueryImpactHit() received NaN/Inf for position",
    "Setup failed",
    "FAILED OPENSL BUFFER Realize",
    "No game present to join for session",
    "No game present to leave for session",
    "Socket->RecvFrom",
    "UNetConnection::Tick: Connection TIMED OUT",
    "UIpNetConnection::LowLevelSend",
    "Your connection to the host has been lost",
    "Unhandled socket error! Error Code: 32. Returning SE_EINVAL!",
    "HTTP POST http://127.0.0.1:9090/LoginWithAccount has failed to connect.",
    "Failed to connect to 127.0.0.1 port 9090: Connection refused",
    "libcurl info message cache",
    "request failed, libcurl error",
    "Host closed the connection",

    "for acquiring GC lock",
    "Failed to get response from login server",
    "TryCollectGarbage: forcing GC after 11 skipped attempts",
    "Function ServerMoveNoBase will not be processed",
    "Last time since Realize Error",
    "SweepSingle resulted in a NaN/INF in PHit",
    "SweepMulti resulted in a NaN/INF in PHit",
    "received NaN/inf for position: nan nan nan",
    "This may cause hitching on the game thread if performed too often",
    "Function ServerMoveDualNoBase will not be processed",
    "SPRenderer: Material 'BasicShapeMaterial' with VF 'FLocalVertexFactory' do not work with SP shaders. Primitive res 'Cube'",
    "to wait for mutex AND trim",
    "to wait for mutex for trim",
    "New Graphics PSO",
    "Encountered a new graphics PSO",
    "UNetDriver::ProcessRemoteFunction: No owning connection for",
    "Using None instead of replicated reference to",
    "Response Header Content-",
    "MoveAlongFloor CurrentFloor is UnWalkable",
    "Native NetSerialize StructProperty /Script/Engine.PlayerController:ServerUpdateCamera.CamLoc (ScriptStruct /Script/Engine.Vector_NetQuantize) failed.",
    "open file failed:",
    "ClientAdjustPosition bAdjust",
    "but it was never saved as an export",
    "is stuck and failed to move",
    "UIpNetDriver::TickDispatch: Took too long to receive packets",
    "Malformed_Packet: Packet failed PacketHandler processing",
    -- 待处理
    -- "SPRenderer: Material 'LODFlattenMaterial' with VF 'FLocalVertexFactory' do not work with SP shaders",
    -- "SPRenderer: Material 'M_Mask_Base_LOD' with VF 'FSplineMeshVertexFactory' do not work with SP shaders",
    "do not work with SP shaders",
    -- 特效的一系列waring wangshuai
    "DX:",
    "DY:",
    "MacroUVPosition",
    "View2",
    "View1",
    "View0",
    "ViewProj",
    "NDCPosY:",
    "NDCPosX:",
    "ObjectNDCPosition",
    "PostProjectionPosition",
    "SystemPositionForMacroUVs",
    "Bad values in FParticleSystemSceneProxy::GetObjectPositionAndScale",

    "SerializeNewActor failed to find/spawn actor. Actor: None, Channel",
    -- ignore by jingzhao
    "PostLoadDeferredObjects Package Can't be Loaded objflag",
    "InternalLoadObject: Unable to resolve object. FullNetGUIDPath",
    "Event_StartPostload export Can't be added to ObjLoaded objflag",
    -- ignore by lihui
    "Component .* at location .* has physics bodies outside of MBP bounds.",

    -- ignore by zhiyuan
    "ThrowAwayItem failed!",

    -- ignore by lihui 只有在执行gm命令的情况下才可能出现超过100人
    "PlayerStatsHelper get award failed, invalid rank",
}

return LogReportWhiteList