local PropNameShip = {}

local function IncludeCommonRepIds()
    local PropNameCommon = require("PropNameCommon")
    local tbIds = PropNameCommon.GetRepIds()
    local tbSelfRepIds = PropNameShip.GetRepIds()
    for _, v in ipairs(tbIds) do
        table.insert(tbSelfRepIds, v)
    end
end

function PropNameShip.Init(Define, T, R)
    IncludeCommonRepIds()

    -- ship property
    Define("bIsShipAlreadyDead",                T.Bool,       R.InitialOnly) -- 必须放bIsShipDead前面，因为需要确保bIsShipAlreadyDead比bIsShipDead先同步下来
    Define("bIsShipDead",                       T.Bool,       R.All)         -- 必须放最前面
    Define("nShipHp",                           T.Float,      R.All)
    Define("nShipEp",                           T.Float,      R.All)
    Define("nShipMaxHpBase",                    T.Float)
    Define("nShipMaxHp",                        T.Float,      R.All)
    Define("nShipMaxEp",                        T.Float,      R.All)
    Define("nShipHpShield",                     T.Float,      R.All)
    Define("bIsShipDying",                      T.Bool,       R.All)
    Define("bIsShipRescuing",                   T.Bool,       R.All)
    Define("nShipMinHpRatio",                   T.Float)
    Define("nMaxLeanDegress",                   T.Float)

    Define("nShipCategory",                     T.Int)
    Define("nFireDamageResistance",             T.Float)
    Define("nLeakDamageResistance",             T.Float)
    Define("nSlowSpeedResistance",              T.Float)
    Define("nStunResistance",                   T.Float)
    Define("nActiveThrownItemTemplateId",       T.Int,        R.OwnerOnly)
    Define("nActiveWeaponSlot",                 T.Int,        R.OwnerOnly)
    Define("nActiveWeaponTemplateId",           T.Int,        R.All)
    Define("nFireSoundReduction",               T.Float,      R.All)
    Define("nTelescopeScale",                   T.Int,        R.All)
    Define("nBulletTriggerRangeRatio",          T.Float)
    Define("nBulletTriggerRangeDelta",          T.Float)
    Define("nBulletMinRadiusDamageAddition",    T.Float)
    Define("nBulletSpeedRatio",                 T.Float,      R.OwnerOnly)
    Define("nBulletSpeedDelta",                 T.Float,      R.OwnerOnly)
    Define("nPerfectFiringRangeBegin",          T.Float)
    Define("nPerfectFiringRangeEnd",            T.Float)
    Define("nWeaponDamageIntervalDelta",        T.Float)
    Define("nWeaponDamageIntervalRatio",        T.Float)
    Define("nCoreDetect",                       T.Int)
    Define("nReloadSpeedDelta",                 T.Float)
    Define("nReloadSpeedRatio",                 T.Float)
    Define("nFiringRangeDelta",                 T.Float,      R.All)
    Define("nFiringRangeRatio",                 T.Float,      R.All)
    Define("nFiringRotationRangeDelta",         T.Float,      R.All)
    Define("nFiringRotationRangeRatio",         T.Float,      R.All)
    Define("nFiringIntervalDelta",              T.Float,      R.OwnerOnly)
    Define("nFiringIntervalRatio",              T.Float,      R.OwnerOnly)
    Define("tbMaterialCollector",               T.Table)
    Define("tbBurningProbInfo",                 T.Table)
    Define("tbLeakingProbInfo",                 T.Table)
    Define("nBurningProb",                      T.Float)
    Define("nLeakingProb",                      T.Float)
    Define("nBurningProofProb",                 T.Float)
    Define("nLeakingProofProb",                 T.Float)
    Define("nBurningDamageRatioCaused",         T.Float)
    Define("nLeakingDamageRatioCaused",         T.Float)
    Define("nBurningDamageRatioTaken",          T.Float)
    Define("nLeakingDamageRatioTaken",          T.Float)
    Define("nControlModeSwitchSpeedRatio",      T.Float)
    Define("tbAttackReductionDamageRatioInfo",  T.Table)
    Define("nShipMaxDyingHp",                   T.Float)
    Define("nShipRescuedHp",                    T.Float)
    Define("nShipDyingHpReduceSpeed",           T.Float)
    Define("nShipRescuedTime",                  T.Float)
    Define("nShipVisibleDistance",              T.Float,      R.All)

    Define("nShipAttack",                       T.Float)
    Define("nShipHeadDamageRatio",              T.Float)
    Define("nShipBodyDamageRatio",              T.Float)
    Define("nShipSternDamageRatio",             T.Float)
    Define("nShipSailDamageRatio",              T.Float)
    Define("nShipDeckDamageRatio",              T.Float)
    Define("nShipCaptainRoomDamageRatio",       T.Float)
    Define("nShipItemUsingTime",                T.Float)
    Define("nShipListenRange",                  T.Float,      R.OwnerOnly)
    Define("nShipPickupRange",                  T.Float,      R.OwnerOnly)
    Define("nShipMoraleConsumedSpeed",          T.Float)
    Define("nShipPartDurability",               T.Float,      R.OwnerOnly)
    Define("nAngularAccelerationAddition",      T.Float)
    Define("nAngularDecelerationAddition",      T.Float)
    Define("nAngularMaxSpeedAddition",          T.Float)
    Define("nLinearAccelerationAddition",       T.Float)
    Define("nLinearDecelerationAddition",       T.Float)
    Define("nLinearMaxSpeedAddition",           T.Float)
    Define("nShipBulletDeviationRatio",         T.Float)
    Define("nShipBulletAimDeviationRatio",      T.Float)
    Define("nShipDebuffTimeRatio",              T.Float)
    Define("nShipRecoveredHpByKilling",         T.Float)
    Define("nShipDamageRatioFromNpc",           T.Float)
    Define("nShipDamageRatioToNpc",             T.Float)
    Define("nShipDamageRatio",                  T.Float)

    -- -- ship avatar
    Define("rShipWeaponResData",                T.Proto,      R.All)
    Define("rShipAvatarResData",                T.Proto,      R.All)
    Define("rShipPartBrokenStatus",             T.Proto,      R.All)
    Define("nShipArmorGrade",                   T.Int,        R.All)

    -- ship battle status component
    Define("nOldShipHp",                        T.Int,        R.All)
    Define("nOldShipEp",                        T.Int,        R.All)
    -- ai is bot
    Define("nShipBotType",                      T.Int,        R.All)
    Define("nShipExtraMaterialCapacityRatio",   T.Float)
    Define("nShipExtraPackageCapacityValue",    T.Int)

    Define("nSmallCannonDamageAddition",        T.Int)
    Define("nPowderKegDamageAddition",          T.Int)
    Define("nCarronadeDamageAddition",          T.Int)
    Define("nTorpedoDamageAddition",            T.Int)
    Define("nSakersDamageAddition",             T.Int)
    Define("nDartleDamageAddition",             T.Int)
    Define("nAssaultGunDamageAddition",         T.Int)
    Define("nSnipeGunDamageAddition",           T.Int)
    Define("nEmbolonDamageAddition",            T.Int)
    Define("nFlamerDamageAddition",             T.Int)
    Define("nSternCannonDamageAddition",        T.Int)
    Define("nPowderKegFiringRoundCountDelta",   T.Int,      R.OwnerOnly)
    Define("nCarronadeFiringRoundCountDelta",   T.Int,      R.OwnerOnly)
    Define("nPowderKegFiringAngleRatio",        T.Float,    R.OwnerOnly)

    -- 船武器装填状态
    Define("rShipWeaponBulletLoadingInfo",      T.Proto,    R.InitialOnly)
end

return PropNameShip