return {
    BATTLE_LIST_ITEM = 1,
    SHIP_WEAPON_SLOT = 2,
    SHIP_PART = 3,
    SHIP_WEAPON_ATTACHMENT = 4,
    HUMAN_WEAPON = 5,
    HUMAN_WEAPON_ATTACHMENT = 6,
    HUMAN_PACKAGE_ITEM = 7,
    HUMAN_ARMOR = 8,
    HUMAN_BAG_SLOT = 9
}