local UITextDef = {}
local UISetUtils = require("UISetUtils")
local GetTextByKey = UISetUtils.GetTextByKey

local ShipWeaponSlotDef = require("ShipWeaponSlotDef")
local ItemCategoryDef = require("ItemCategoryDef")
local HumanAvatarDef = require("HumanAvatarDef")

local GetL10NTextByKey = UISetUtils.GetL10NTextByKey

-- Text 定义在 client\ui\text 目录下

UITextDef.FRIEND_ADD_SELF_FULL = GetL10NTextByKey("FRIEND_ADD_SELF_FULL")
UITextDef.APPLY_FRIEND_LIMIT = GetL10NTextByKey("APPLY_FRIEND_LIMIT")
UITextDef.OTHER_APPLY_FRIEND_LIMIT = GetL10NTextByKey("OTHER_APPLY_FRIEND_LIMIT")
UITextDef.OTHER_FRIEND_COUNT_LIMIT = GetL10NTextByKey("OTHER_FRIEND_COUNT_LIMIT")
UITextDef.FRIEND_NOT_FOUND = GetL10NTextByKey("FRIEND_NOT_FOUND")
UITextDef.ALREADY_IN_APPLY_FRIEND = GetL10NTextByKey("ALREADY_IN_APPLY_FRIEND")
UITextDef.FRIEND_CANNOT_ADD_SELF = GetL10NTextByKey("FRIEND_CANNOT_ADD_SELF")
UITextDef.ALREADY_IN_FRIEND = GetL10NTextByKey("ALREADY_IN_FRIEND")
UITextDef.OTHER_NOT_IN_APPLY_LIST = GetL10NTextByKey("OTHER_NOT_IN_APPLY_LIST")
UITextDef.APPLY_FRIEND_MSG_EMPTY = GetL10NTextByKey("APPLY_FRIEND_MSG_EMPTY")
UITextDef.APPLY_FRIEND_LIST_EMPTY = GetL10NTextByKey("APPLY_FRIEND_LIST_EMPTY")
UITextDef.FRIEND_LIST_EMPTY = GetL10NTextByKey("FRIEND_LIST_EMPTY")
UITextDef.OTHER_NOT_FRIEND = GetL10NTextByKey("OTHER_NOT_FRIEND")
UITextDef.FRIEND_DB_ERROR = GetL10NTextByKey("FRIEND_DB_ERROR")
UITextDef.FRIEND_APPLY_SUCCESS = GetL10NTextByKey("FRIEND_APPLY_SUCCESS")
UITextDef.BLACK_LIST_EMPTY = GetL10NTextByKey("BLACK_LIST_EMPTY")

UITextDef.PLAYER_NOT_IN_APPLY_LIST = GetL10NTextByKey("PLAYER_NOT_IN_APPLY_LIST")
UITextDef.L10N_YOU = GetL10NTextByKey("L10N_YOU")
UITextDef.RECHECKIN_MESSAGE = GetL10NTextByKey("RECHECKIN_MESSAGE")
UITextDef.SCHEDULE_SHIP_GRADE_NOT_ENOUGH = GetL10NTextByKey("SCHEDULE_SHIP_GRADE_NOT_ENOUGH")
UITextDef.TEAM_JOIN_REQUEST_LIST_FULL = GetL10NTextByKey("TEAM_JOIN_REQUEST_LIST_FULL")
UITextDef.QUEST_MAIN = GetL10NTextByKey("QUEST_MAIN")
UITextDef.TEAM_INVITE_REPLY_FULL = GetL10NTextByKey("TEAM_INVITE_REPLY_FULL")
UITextDef.QUEST_ACCEPT_OP = GetL10NTextByKey("QUEST_ACCEPT_OP")
UITextDef.SOCIETY_PRIVATEER_QUIT_DUNGEON_MESSAGE = GetL10NTextByKey("SOCIETY_PRIVATEER_QUIT_DUNGEON_MESSAGE")
UITextDef.PVE01_QUIT_DUNGEON_TITLE = GetL10NTextByKey("PVE01_QUIT_DUNGEON_TITLE")
UITextDef.SHIP_LOW_REPAIR = GetL10NTextByKey("SHIP_LOW_REPAIR")
UITextDef.GREEN_ARROW = GetL10NTextByKey("GREEN_ARROW")
UITextDef.L10N_FREQUENT_OP = GetL10NTextByKey("L10N_FREQUENT_OP")
UITextDef.TRANSFER_POINT_NAME =
{
    [4] = GetL10NTextByKey("TRANSFER_POINT_NAME4"),
    [1] = GetL10NTextByKey("TRANSFER_POINT_NAME1"),
    [2] = GetL10NTextByKey("TRANSFER_POINT_NAME2"),
    [3] = GetL10NTextByKey("TRANSFER_POINT_NAME3"),
}
UITextDef.PROVOCATIVE_QUIT_DUNGEON_LIMIT_MESSAGE = GetL10NTextByKey("PROVOCATIVE_QUIT_DUNGEON_LIMIT_MESSAGE")
UITextDef.TEAM_JOIN_INVALID_TEAM = GetL10NTextByKey("TEAM_JOIN_INVALID_TEAM")
UITextDef.CONDITION_LIMIT = GetL10NTextByKey("CONDITION_LIMIT")
UITextDef.TRADE_CAPACILITY_LIMIT = GetL10NTextByKey("TRADE_CAPACILITY_LIMIT")
UITextDef.TRADE_FORBIDDEN_SELL_CARGO = GetL10NTextByKey("TRADE_FORBIDDEN_SELL_CARGO")
UITextDef.TEAM_INVITE_IN_LIST = GetL10NTextByKey("TEAM_INVITE_IN_LIST")
UITextDef.L10N_OK = GetL10NTextByKey("L10N_OK")
UITextDef.L10N_SPLIT_DESC = GetL10NTextByKey("L10N_SPLIT_DESC")
UITextDef.TEAM_MAIN_ITEM_NOT_OPEN_INFO = GetL10NTextByKey("TEAM_MAIN_ITEM_NOT_OPEN_INFO")
UITextDef.GO_TO_SEA_FAIL_NOT_ENOUGH_DURABILITY = GetL10NTextByKey("GO_TO_SEA_FAIL_NOT_ENOUGH_DURABILITY")
UITextDef.L10N_HIDE_ITEM_RES_FAIL = GetL10NTextByKey("L10N_HIDE_ITEM_RES_FAIL")
UITextDef.COMMAND_CANCEL = GetL10NTextByKey("COMMAND_CANCEL")
UITextDef.SHIP_REPAIR_TITEL = GetL10NTextByKey("SHIP_REPAIR_TITEL")
UITextDef.L10N_SELECT_ACCESSORY_SUCCESS = GetL10NTextByKey("L10N_SELECT_ACCESSORY_SUCCESS")
UITextDef.TEAM_JOIN_OTHER_IN_TEAM = GetL10NTextByKey("TEAM_JOIN_OTHER_IN_TEAM")
UITextDef.USER_NAME_LEN_ERROR = GetL10NTextByKey("USER_NAME_LEN_ERROR")
UITextDef.PVE02_QUIT_DUNGEON_MESSAGE = GetL10NTextByKey("PVE02_QUIT_DUNGEON_MESSAGE")
UITextDef.FISHING_FAILED = GetL10NTextByKey("FISHING_FAILED")
UITextDef.SHIP_REPAIR_SUCCESS = GetL10NTextByKey("SHIP_REPAIR_SUCCESS")
UITextDef.MINIGAME_DRINKING_TITLE = GetL10NTextByKey("MINIGAME_DRINKING_TITLE")
UITextDef.NO_MAX_COUNT = GetL10NTextByKey("NO_MAX_COUNT")
UITextDef.REFRESH_COUNT_MAX = GetL10NTextByKey("REFRESH_COUNT_MAX")
UITextDef.QUEST_FAILURE = GetL10NTextByKey("QUEST_FAILURE")
UITextDef.L10N_GAINED_EXP = GetL10NTextByKey("L10N_GAINED_EXP")
UITextDef.ASSOCIATION_NO_ENOUGH_ENTRUST_LETTER = GetL10NTextByKey("ASSOCIATION_NO_ENOUGH_ENTRUST_LETTER")
UITextDef.FACTION_PLAYER_TEAM = GetL10NTextByKey("FACTION_PLAYER_TEAM")
UITextDef.LOGIN_ANNOUNCEMENT = GetL10NTextByKey("LOGIN_ANNOUNCEMENT")
UITextDef.TEAM_INVITE_IN_TEAM = GetL10NTextByKey("TEAM_INVITE_IN_TEAM")
UITextDef.SMUGGLE_QUIT_DUNGEON_TITLE = GetL10NTextByKey("SMUGGLE_QUIT_DUNGEON_TITLE")
UITextDef.FFA_QUIT_DUNGEON_TITLE = GetL10NTextByKey("FFA_QUIT_DUNGEON_TITLE")
UITextDef.FFA_QUIT_DUNGEON_MESSAGE = GetL10NTextByKey("FFA_QUIT_DUNGEON_MESSAGE")
UITextDef.FFA_QUIT_TRAININGCAMP_DUNGEON_MESSAGE = GetL10NTextByKey("FFA_QUIT_TRAININGCAMP_DUNGEON_MESSAGE")
UITextDef.SHIP_CANCLE_REPAIR = GetL10NTextByKey("SHIP_CANCLE_REPAIR")
UITextDef.TEAM_JOIN_OTHER_IN_FIGHT = GetL10NTextByKey("TEAM_JOIN_OTHER_IN_FIGHT")
UITextDef.L10N_INVALID_ATTACK = GetL10NTextByKey("L10N_INVALID_ATTACK")
UITextDef.L10N_INFORMATION_TIP = GetL10NTextByKey("L10N_INFORMATION_TIP")
UITextDef.tbL10N_CheckReturn =
{
    [1] = GetL10NTextByKey("tbL10N_CheckReturn1"),
    [2] = GetL10NTextByKey("tbL10N_CheckReturn2"),
    [3] = GetL10NTextByKey("tbL10N_CheckReturn3"),
    [4] = GetL10NTextByKey("tbL10N_CheckReturn4"),
    [5] = GetL10NTextByKey("tbL10N_CheckReturn5"),
}
UITextDef.CANNOT_RESET_BACKPACK_FULL = GetL10NTextByKey("CANNOT_RESET_BACKPACK_FULL")
UITextDef.CANNOT_REPLACE_BACKPACK_FULL = GetL10NTextByKey("CANNOT_REPLACE_BACKPACK_FULL")
UITextDef.CAMERA_SHOT_SUCCESS = GetL10NTextByKey("CAMERA_SHOT_SUCCESS")
UITextDef.PLAYER_UNAVAILALE = GetL10NTextByKey("PLAYER_UNAVAILALE")
UITextDef.WELFARE_GET_BACK_FAIL_BACKPACK_FULL = GetL10NTextByKey("WELFARE_GET_BACK_FAIL_BACKPACK_FULL")
UITextDef.SOCIETY_GUARD_QUIT_DUNGEON_MESSAGE = GetL10NTextByKey("SOCIETY_GUARD_QUIT_DUNGEON_MESSAGE")
UITextDef.NOT_ENOUGH_BAIT = GetL10NTextByKey("NOT_ENOUGH_BAIT")
UITextDef.TEAM_INVITE_INVALID_REPLY = GetL10NTextByKey("TEAM_INVITE_INVALID_REPLY")
UITextDef.NO_NEXT_VALID_TARGET = GetL10NTextByKey("NO_NEXT_VALID_TARGET")
UITextDef.MINIGAME_RUBBING_PROCESS = GetL10NTextByKey("MINIGAME_RUBBING_PROCESS")
UITextDef.QUEST_ABORT_DESC = GetL10NTextByKey("QUEST_ABORT_DESC")
UITextDef.L10N_CANNOT_CHANGE_ITEM_RES = GetL10NTextByKey("L10N_CANNOT_CHANGE_ITEM_RES")
UITextDef.MINIGAME_RUBBING_PROCESS_COUNT = GetL10NTextByKey("MINIGAME_RUBBING_PROCESS_COUNT")
UITextDef.PERFORMANCE_LEVEL_DESC =
{
    [0] = GetL10NTextByKey("PERFORMANCE_LEVEL_DESC0"),
    [1] = GetL10NTextByKey("PERFORMANCE_LEVEL_DESC1"),
    [2] = GetL10NTextByKey("PERFORMANCE_LEVEL_DESC2"),
}
UITextDef.SHIP_ADD_SUPPLY_FAILED_GOLD_SUPPLY_IS_MORE = GetL10NTextByKey("SHIP_ADD_SUPPLY_FAILED_GOLD_SUPPLY_IS_MORE")
UITextDef.SAIL_DISABLE = GetL10NTextByKey("SAIL_DISABLE")
UITextDef.FRIEND_ALREADY_BLACK_LIST = GetL10NTextByKey("FRIEND_ALREADY_BLACK_LIST")
UITextDef.CHECKIN_MAX = GetL10NTextByKey("CHECKIN_MAX")
UITextDef.LIVENESS_TODAY = GetL10NTextByKey("LIVENESS_TODAY")
UITextDef.ACCOUNT_LEN_ERROR = GetL10NTextByKey("ACCOUNT_LEN_ERROR")
UITextDef.SIDE_QUEST_01_QUIT_DUNGEON_TITLE = GetL10NTextByKey("SIDE_QUEST_01_QUIT_DUNGEON_TITLE")
UITextDef.NEXT_STAGE_COUNT_DOWN = GetL10NTextByKey("NEXT_STAGE_COUNT_DOWN")
UITextDef.PVE01_QUIT_DUNGEON_MESSAGE = GetL10NTextByKey("PVE01_QUIT_DUNGEON_MESSAGE")
UITextDef.DUNGEONPVE_QUIT_DUNGEON_TITLE = GetL10NTextByKey("DUNGEONPVE_QUIT_DUNGEON_TITLE")
UITextDef.NO_TARGET = GetL10NTextByKey("NO_TARGET")
UITextDef.ASSOCIATION_CANNOT_OPEN_UI = GetL10NTextByKey("ASSOCIATION_CANNOT_OPEN_UI")
UITextDef.TRADE_MONEY_LIMIT = GetL10NTextByKey("TRADE_MONEY_LIMIT")
UITextDef.FACTION_CHANGE = GetL10NTextByKey("FACTION_CHANGE")
UITextDef.RED_ARROW = GetL10NTextByKey("RED_ARROW")
UITextDef.QUEST_ASSOCIATION = GetL10NTextByKey("QUEST_ASSOCIATION")
UITextDef.PVE02_QUIT_DUNGEON_TITLE = GetL10NTextByKey("PVE02_QUIT_DUNGEON_TITLE")
UITextDef.SHIP_REPAIR_DURABILITY_IS_FULL = GetL10NTextByKey("SHIP_REPAIR_DURABILITY_IS_FULL")
UITextDef.ASSOCIATION_QUIT_DUNGEON_MESSAGE = GetL10NTextByKey("ASSOCIATION_QUIT_DUNGEON_MESSAGE")
UITextDef.QUEST_COMPLETE_DESC_SHARED = GetL10NTextByKey("QUEST_COMPLETE_DESC_SHARED")
UITextDef.NOT_ENOUGH_GOLD = GetL10NTextByKey("NOT_ENOUGH_GOLD")
UITextDef.RANK_NOT_IN_BOARD_TXT = GetL10NTextByKey("RANK_NOT_IN_BOARD_TXT")
UITextDef.ASSOCIATION_REFRESH_DESC = GetL10NTextByKey("ASSOCIATION_REFRESH_DESC")
UITextDef.PASSWQRLD_EMPTY = GetL10NTextByKey("PASSWQRLD_EMPTY")
UITextDef.CONQUEST_QUIT_DUNGEON_TITLE = GetL10NTextByKey("CONQUEST_QUIT_DUNGEON_TITLE")
UITextDef.DISCONNECT_SERVER_MAINTENANCE = GetL10NTextByKey("DISCONNECT_SERVER_MAINTENANCE")
UITextDef.TEAM_JOIN_REQUEST_TEAM_FULL = GetL10NTextByKey("TEAM_JOIN_REQUEST_TEAM_FULL")
UITextDef.TRADE_OUTDATED_DATA = GetL10NTextByKey("TRADE_OUTDATED_DATA")
UITextDef.TEAM_JOIN_INVALID_REQUEST = GetL10NTextByKey("TEAM_JOIN_INVALID_REQUEST")
UITextDef.REFUSE_JOIN_TEAM = GetL10NTextByKey("REFUSE_JOIN_TEAM")
UITextDef.BATTLEGROUND_FAILED_MEMBERSCENE = GetL10NTextByKey("BATTLEGROUND_FAILED_MEMBERSCENE")
UITextDef.TOWN_PORTAL_OK = GetL10NTextByKey("TOWN_PORTAL_OK")
UITextDef.QUEST_COMPLETE_OP = GetL10NTextByKey("QUEST_COMPLETE_OP")
UITextDef.BATTLEGROUND_MATCH_DISCONNECT = GetL10NTextByKey("BATTLEGROUND_MATCH_DISCONNECT")
UITextDef.L10N_RESET_ACCESSORY_SUCCESS = GetL10NTextByKey("L10N_RESET_ACCESSORY_SUCCESS")
UITextDef.WELFARE_GET_BACK_COUNT = GetL10NTextByKey("WELFARE_GET_BACK_COUNT")
UITextDef.QUEST_GUIDE = GetL10NTextByKey("QUEST_GUIDE")
UITextDef.MINIGAME_SKIP_CONFIRM = GetL10NTextByKey("MINIGAME_SKIP_CONFIRM")
UITextDef.DAY_NUM = GetL10NTextByKey("DAY_NUM")
UITextDef.QUICK_MATCH_TITLE = GetL10NTextByKey("QUICK_MATCH_TITLE")
UITextDef.SHIP_CHANGE_SUCCESS = GetL10NTextByKey("SHIP_CHANGE_SUCCESS")
UITextDef.TEAM_MAIN_ITEM_NOT_OPEN_NEARBY = GetL10NTextByKey("TEAM_MAIN_ITEM_NOT_OPEN_NEARBY")
UITextDef.L10N_SELECT_CONSUMABLE_SUCCESS = GetL10NTextByKey("L10N_SELECT_CONSUMABLE_SUCCESS")
UITextDef.L10N_GAINED_ITEM_CHAT = GetL10NTextByKey("L10N_GAINED_ITEM_CHAT")
UITextDef.MINIGAME_RUBBING_TITLE = GetL10NTextByKey("MINIGAME_RUBBING_TITLE")
UITextDef.SHIP_CHANGE_FAILED_FLAG_SHIP_ALREADY = GetL10NTextByKey("SHIP_CHANGE_FAILED_FLAG_SHIP_ALREADY")
UITextDef.TEAM_INVITE_REPLY_FACTION = GetL10NTextByKey("TEAM_INVITE_REPLY_FACTION")
UITextDef.QUEST_ACCEPT_DESC = GetL10NTextByKey("QUEST_ACCEPT_DESC")
UITextDef.WELFARE_GET_BACK_COST = GetL10NTextByKey("WELFARE_GET_BACK_COST")
UITextDef.NOT_ENOUGH_SILVER = GetL10NTextByKey("NOT_ENOUGH_SILVER")
UITextDef.BIG_FISHPOINT_END = GetL10NTextByKey("BIG_FISHPOINT_END")
UITextDef.ACTIVE_SKILL = GetL10NTextByKey("ACTIVE_SKILL")
UITextDef.FRIEND_APPLY_FULL = GetL10NTextByKey("FRIEND_APPLY_FULL")
UITextDef.BATTLEGROUND_FAILED_MEMBERSHIPGRADE = GetL10NTextByKey("BATTLEGROUND_FAILED_MEMBERSHIPGRADE")
UITextDef.ARENA_DEAD_QUIT_DUNGEON_MESSAGE = GetL10NTextByKey("ARENA_DEAD_QUIT_DUNGEON_MESSAGE")
UITextDef.DUNGEON_DROPPED_FROM_HUB = GetL10NTextByKey("DUNGEON_DROPPED_FROM_HUB")
UITextDef.MINIGAME_CLOSE = GetL10NTextByKey("MINIGAME_CLOSE")
UITextDef.L10N_RESET_CONSUMABLE_SUCCESS = GetL10NTextByKey("L10N_RESET_CONSUMABLE_SUCCESS")
UITextDef.NOT_NEED_REFRESH = GetL10NTextByKey("NOT_NEED_REFRESH")
UITextDef.RECHECKIN_COST = GetL10NTextByKey("RECHECKIN_COST")
UITextDef.WELFARE_TREASURE_GOLD_NOT_ENOUGH = GetL10NTextByKey("WELFARE_TREASURE_GOLD_NOT_ENOUGH")
UITextDef.SCHEDULE_TEAM = GetL10NTextByKey("SCHEDULE_TEAM")
UITextDef.FACTION_TITLE = GetL10NTextByKey("FACTION_TITLE")
UITextDef.BUY_COUNT_LIMIT = GetL10NTextByKey("BUY_COUNT_LIMIT")
UITextDef.LOGIN_HELP = GetL10NTextByKey("LOGIN_HELP")
UITextDef.DISCONNECT_DOUBLE_LOGIN = GetL10NTextByKey("DISCONNECT_DOUBLE_LOGIN")
UITextDef.DISCONNECT_FROM_DUNGEONSERVER = GetL10NTextByKey("DISCONNECT_FROM_DUNGEONSERVER")
UITextDef.CHAt_NO_TEAM = GetL10NTextByKey("CHAt_NO_TEAM")
UITextDef.BATTLEGROUND_FAILED_MEMBERFORBIDDENBUFF = GetL10NTextByKey("BATTLEGROUND_FAILED_MEMBERFORBIDDENBUFF")
UITextDef.CHAT_ONLINE_LIMIT = GetL10NTextByKey("CHAT_ONLINE_LIMIT")
UITextDef.FACTION_PLAYER_LEVEL = GetL10NTextByKey("FACTION_PLAYER_LEVEL")
UITextDef.TEAM_INVITE_LIST_FULL = GetL10NTextByKey("TEAM_INVITE_LIST_FULL")
UITextDef.TEAM_MAIN_ITEM_OFFLINE = GetL10NTextByKey("TEAM_MAIN_ITEM_OFFLINE")
UITextDef.TEAM_JOIN_OTHER_NOT_ONLINE = GetL10NTextByKey("TEAM_JOIN_OTHER_NOT_ONLINE")
UITextDef.L10N_ACCESSORY_DELETE = GetL10NTextByKey("L10N_ACCESSORY_DELETE")
UITextDef.L10N_REPLACE_CONSUMABLE_SUCCESS = GetL10NTextByKey("L10N_REPLACE_CONSUMABLE_SUCCESS")
UITextDef.NOT_ENOUGH_LEVLE = GetL10NTextByKey("NOT_ENOUGH_LEVLE")
UITextDef.L10N_GAINED_SHIP = GetL10NTextByKey("L10N_GAINED_SHIP")
UITextDef.L10N_NOT_HIDE_ITEM_RES_FAIL = GetL10NTextByKey("L10N_NOT_HIDE_ITEM_RES_FAIL")
UITextDef.L10N_REPARI_DISABLE = GetL10NTextByKey("L10N_REPARI_DISABLE")
UITextDef.BATTLEGROUND_FAILED_TEAMSIZE = GetL10NTextByKey("BATTLEGROUND_FAILED_TEAMSIZE")
UITextDef.L10N_EQUIP_MATCH_GRADE = GetL10NTextByKey("L10N_EQUIP_MATCH_GRADE")
UITextDef.NOT_ENOUGH_ITEM = GetL10NTextByKey("NOT_ENOUGH_ITEM")
UITextDef.BATTLE_EXIT_COUNT_DOWN = GetL10NTextByKey("BATTLE_EXIT_COUNT_DOWN")
UITextDef.BUY_TIME_LIMIT = GetL10NTextByKey("BUY_TIME_LIMIT")
UITextDef.TEAM_JION_TEAM = GetL10NTextByKey("TEAM_JION_TEAM")
UITextDef.L10N_Cancel = GetL10NTextByKey("L10N_Cancel")
UITextDef.DISCONNECT_SERVER_TORECONNECT = GetL10NTextByKey("DISCONNECT_SERVER_TORECONNECT")
UITextDef.INVALID_GOODS_ID = GetL10NTextByKey("INVALID_GOODS_ID")
UITextDef.DISCONNECT_SERVER_UNKNOWN = GetL10NTextByKey("DISCONNECT_SERVER_UNKNOWN")
UITextDef.TEAM_INVITE_FACTION = GetL10NTextByKey("TEAM_INVITE_FACTION")
UITextDef.WELFARE_GET_BACK_SUCCESS = GetL10NTextByKey("WELFARE_GET_BACK_SUCCESS")
UITextDef.SCHEDULE_SINGLE_OR_TEAM = GetL10NTextByKey("SCHEDULE_SINGLE_OR_TEAM")
UITextDef.L10N_GAINED_ITEM = GetL10NTextByKey("L10N_GAINED_ITEM")
UITextDef.BATTLEGROUND_FAILED_TEAMLEADER = GetL10NTextByKey("BATTLEGROUND_FAILED_TEAMLEADER")
UITextDef.L10N_PERSONAL = GetL10NTextByKey("L10N_PERSONAL")
UITextDef.TRADE_SELL = GetL10NTextByKey("TRADE_SELL")
UITextDef.TEAM_INVITE_OTHER_NOT_ONLINE = GetL10NTextByKey("TEAM_INVITE_OTHER_NOT_ONLINE")
UITextDef.ASSOCIATION_FREE_REFRESH = GetL10NTextByKey("ASSOCIATION_FREE_REFRESH")
UITextDef.COMMAND_QUICK = GetL10NTextByKey("COMMAND_QUICK")
UITextDef.TRADE_COST = GetL10NTextByKey("TRADE_COST")
UITextDef.CONQUEST_QUIT_DUNGEON_MESSAGE = GetL10NTextByKey("CONQUEST_QUIT_DUNGEON_MESSAGE")
UITextDef.ASSOCIATION_QUIT_DUNGEON_TITLE = GetL10NTextByKey("ASSOCIATION_QUIT_DUNGEON_TITLE")
UITextDef.BATTLE_BE_CALLED_NAME = GetL10NTextByKey("BATTLE_BE_CALLED_NAME")
UITextDef.DUNGEONPVE_QUIT_DUNGEON_MESSAGE = GetL10NTextByKey("DUNGEONPVE_QUIT_DUNGEON_MESSAGE")
UITextDef.FRIEND_NO_RECOMMEND = GetL10NTextByKey("FRIEND_NO_RECOMMEND")
UITextDef.INVALID_SHOP_ID = GetL10NTextByKey("INVALID_SHOP_ID")
UITextDef.SIDE_QUEST_01_QUIT_DUNGEON_MESSAGE = GetL10NTextByKey("SIDE_QUEST_01_QUIT_DUNGEON_MESSAGE")
UITextDef.SHIP_REPAIR_FAILED_NOT_FLAG_SHIP = GetL10NTextByKey("SHIP_REPAIR_FAILED_NOT_FLAG_SHIP")
UITextDef.BATTLEGROUND_FAILED_NOTOPEN = GetL10NTextByKey("BATTLEGROUND_FAILED_NOTOPEN")
UITextDef.SCHEDULE_NO_CONDITON = GetL10NTextByKey("SCHEDULE_NO_CONDITON")
UITextDef.L10N_REPLACE_ACCESSORY_SUCCESS = GetL10NTextByKey("L10N_REPLACE_ACCESSORY_SUCCESS")
UITextDef.SHIP_PART_BUFF_MESSAGE =
{
    [1] = GetL10NTextByKey("SHIP_PART_BUFF_MESSAGE1"),
    [2] = GetL10NTextByKey("SHIP_PART_BUFF_MESSAGE2"),
    [3] = GetL10NTextByKey("SHIP_PART_BUFF_MESSAGE3"),
    [4] = GetL10NTextByKey("SHIP_PART_BUFF_MESSAGE4"),
    [5] = GetL10NTextByKey("SHIP_PART_BUFF_MESSAGE5"),
}
UITextDef.FRIEND_SEARCH_FAILURE = GetL10NTextByKey("FRIEND_SEARCH_FAILURE")
UITextDef.CHAT_LEVEL_LIMIT = GetL10NTextByKey("CHAT_LEVEL_LIMIT")
UITextDef.ACCOUNT_EMPTY = GetL10NTextByKey("ACCOUNT_EMPTY")
UITextDef.SHIP_CHANGE_FAILED_NOT_IN_LAND = GetL10NTextByKey("SHIP_CHANGE_FAILED_NOT_IN_LAND")
UITextDef.CHAT_SYSTEM_TAG = GetL10NTextByKey("CHAT_SYSTEM_TAG")
UITextDef.TEAM_JOIN_IN_REQUEST_LIST = GetL10NTextByKey("TEAM_JOIN_IN_REQUEST_LIST")
UITextDef.GUIDE_PLAYER_NAME_DIALOGUE = GetL10NTextByKey("GUIDE_PLAYER_NAME_DIALOGUE")
UITextDef.PROVOCATIVE_QUIT_DUNGEON_TITLE = GetL10NTextByKey("PROVOCATIVE_QUIT_DUNGEON_TITLE")
UITextDef.SCHEDULE_FAIL_NOT_ENOUGH_LEVEL = GetL10NTextByKey("SCHEDULE_FAIL_NOT_ENOUGH_LEVEL")
UITextDef.WELFARE_GET_BACK_DIALOG_MESSAGE_PERFECT = GetL10NTextByKey("WELFARE_GET_BACK_DIALOG_MESSAGE_PERFECT")
UITextDef.INTERATION_BUTTON_TEXT =
{
    [1] = GetL10NTextByKey("INTERATION_BUTTON_TEXT1"),
    [2] = GetL10NTextByKey("INTERATION_BUTTON_TEXT2"),
    [3] = GetL10NTextByKey("INTERATION_BUTTON_TEXT3"),
    [4] = GetL10NTextByKey("INTERATION_BUTTON_TEXT4"),
    [5] = GetL10NTextByKey("INTERATION_BUTTON_TEXT5"),
    [6] = GetL10NTextByKey("INTERATION_BUTTON_TEXT6"),
    [7] = GetL10NTextByKey("INTERATION_BUTTON_TEXT7"),
    [8] = GetL10NTextByKey("INTERATION_BUTTON_TEXT8"),
    [9] = GetL10NTextByKey("INTERATION_BUTTON_TEXT9"),
    [10] = GetL10NTextByKey("INTERATION_BUTTON_TEXT10"),
    [11] = GetL10NTextByKey("INTERATION_BUTTON_TEXT11"),
    [12] = GetL10NTextByKey("INTERATION_BUTTON_TEXT12"),
    [13] = GetL10NTextByKey("INTERATION_BUTTON_TEXT13"),
}
UITextDef.QUEST_DELETE_DESC_SHARED = GetL10NTextByKey("QUEST_DELETE_DESC_SHARED")
UITextDef.GO_TO_SEA_SUCCESS = GetL10NTextByKey("GO_TO_SEA_SUCCESS")
UITextDef.TEAM_JOIN_FACTION = GetL10NTextByKey("TEAM_JOIN_FACTION")
UITextDef.SHIP_ADD_SUPPLY_SUCCESS_LOW_LEVEL_WELFARE = GetL10NTextByKey("SHIP_ADD_SUPPLY_SUCCESS_LOW_LEVEL_WELFARE")
UITextDef.ESCORT_QUIT_DUNGEON_MESSAGE = GetL10NTextByKey("ESCORT_QUIT_DUNGEON_MESSAGE")
UITextDef.LOGIN_FAIL = GetL10NTextByKey("LOGIN_FAIL")
UITextDef.REVISION_CHECK_FAILED = GetL10NTextByKey("REVISION_CHECK_FAILED")
UITextDef.FRIEND_APPLY_ALREADY = GetL10NTextByKey("FRIEND_APPLY_ALREADY")
UITextDef.FACTION_CANCLE = GetL10NTextByKey("FACTION_CANCLE")
UITextDef.L10N_OCCUPY_END = GetL10NTextByKey("L10N_OCCUPY_END")
UITextDef.NAME_UNAVAILABLE = GetL10NTextByKey("NAME_UNAVAILABLE")
UITextDef.ACCOUNT_ILLEGAL = GetL10NTextByKey("ACCOUNT_ILLEGAL")
UITextDef.L10N_OCCUPY_BEGIN = GetL10NTextByKey("L10N_OCCUPY_BEGIN")
UITextDef.NAME_ILLEGAL = GetL10NTextByKey("NAME_ILLEGAL")
UITextDef.CHAT_DUNGEON_TAG = GetL10NTextByKey("CHAT_DUNGEON_TAG")
UITextDef.RUDDER_BROKEN_TIPS = GetL10NTextByKey("RUDDER_BROKEN_TIPS")
UITextDef.UNKNOW_ERROR_FORMAT = GetL10NTextByKey("UNKNOW_ERROR_FORMAT")
UITextDef.BATTLE_PLAYER_DEAD = GetL10NTextByKey("BATTLE_PLAYER_DEAD")
UITextDef.L10N_EXIT_GAME = GetL10NTextByKey("L10N_EXIT_GAME")
UITextDef.SCHEDULE_SINGLE = GetL10NTextByKey("SCHEDULE_SINGLE")
UITextDef.TOWN_PORTAL_TITLE = GetL10NTextByKey("TOWN_PORTAL_TITLE")
UITextDef.CURRENCY_NOT_ENOUGH = GetL10NTextByKey("CURRENCY_NOT_ENOUGH")
UITextDef.TEAM_JOIN_REPLY_FACTION = GetL10NTextByKey("TEAM_JOIN_REPLY_FACTION")
UITextDef.TRADE_FULL_CABIN = GetL10NTextByKey("TRADE_FULL_CABIN")
UITextDef.FACTION_QUIT_DUNGEON_TITLE = GetL10NTextByKey("FACTION_QUIT_DUNGEON_TITLE")
UITextDef.ONLINE_TIME = GetL10NTextByKey("ONLINE_TIME")
UITextDef.FRIEND_ADD_NOTIFY = GetL10NTextByKey("FRIEND_ADD_NOTIFY")
UITextDef.L10N_GAINED_CURRENCY = GetL10NTextByKey("L10N_GAINED_CURRENCY")
UITextDef.BATTLE_AUTO_FIGHTING_TIPS = GetL10NTextByKey("BATTLE_AUTO_FIGHTING_TIPS")
UITextDef.ASSOCIATION_TITLE = GetL10NTextByKey("ASSOCIATION_TITLE")
UITextDef.FRIEND_ALREADY = GetL10NTextByKey("FRIEND_ALREADY")
UITextDef.SCHEDULE_COMPLETE = GetL10NTextByKey("SCHEDULE_COMPLETE")
UITextDef.L10N_GAINED_SILVER = GetL10NTextByKey("L10N_GAINED_SILVER")
UITextDef.TEAM_JOINTEAMSUCCESS = GetL10NTextByKey("TEAM_JOINTEAMSUCCESS")
UITextDef.FACTION_PLAYER_SCENE = GetL10NTextByKey("FACTION_PLAYER_SCENE")
UITextDef.STACK_MAX = GetL10NTextByKey("STACK_MAX")
UITextDef.AUTO_ROAD_SHIP = GetL10NTextByKey("AUTO_ROAD_SHIP")
UITextDef.PVP_LEVEL_LIMIT = GetL10NTextByKey("PVP_LEVEL_LIMIT")
UITextDef.QUEST_EXPLORE = GetL10NTextByKey("QUEST_EXPLORE")
UITextDef.L10N_COUNT_DOWN_FORMAT =
{
    [4] = GetTextByKey("L10N_COUNT_DOWN_FORMAT4"),
    [1] = GetTextByKey("L10N_COUNT_DOWN_FORMAT1"),
    [2] = GetTextByKey("L10N_COUNT_DOWN_FORMAT2"),
    [3] = GetTextByKey("L10N_COUNT_DOWN_FORMAT3"),
}
UITextDef.ShipCategoryLevel = GetL10NTextByKey("ShipCategoryLevel")
UITextDef.QUEST_ACTIVITY = GetL10NTextByKey("QUEST_ACTIVITY")
UITextDef.MINIGAME_SKIP = GetL10NTextByKey("MINIGAME_SKIP")
UITextDef.WELFARE_GET_BACK_DIALOG_TITLE = GetL10NTextByKey("WELFARE_GET_BACK_DIALOG_TITLE")
UITextDef.BATTLEGROUND_FAILED_MEMBERSTATE = GetL10NTextByKey("BATTLEGROUND_FAILED_MEMBERSTATE")
UITextDef.SCHEDULE_CLOSED = GetL10NTextByKey("SCHEDULE_CLOSED")
UITextDef.WELFARE_WAIT_TIME = GetL10NTextByKey("WELFARE_WAIT_TIME")
UITextDef.INVALID_REQUEST = GetL10NTextByKey("INVALID_REQUEST")
UITextDef.DISCONNECT_SERVER_MAINTENANCE_LOGIN = GetL10NTextByKey("DISCONNECT_SERVER_MAINTENANCE_LOGIN")
UITextDef.BATTLEGROUND_FAILED_MEMBERONLINE = GetL10NTextByKey("BATTLEGROUND_FAILED_MEMBERONLINE")
UITextDef.FACTION_INVALID = GetL10NTextByKey("FACTION_INVALID")
UITextDef.TEAM_INVITE_IN_FIGHT = GetL10NTextByKey("TEAM_INVITE_IN_FIGHT")
UITextDef.L10N_GAINED_MODPART_RUBBLE = GetL10NTextByKey("L10N_GAINED_MODPART_RUBBLE")
UITextDef.L10N_SPLIT_TITLE = GetL10NTextByKey("L10N_SPLIT_TITLE")
UITextDef.TEAM_PLAYER_JION_TEAM = GetL10NTextByKey("TEAM_PLAYER_JION_TEAM")
UITextDef.PLAYER_COUNT_LIMIT = GetL10NTextByKey("PLAYER_COUNT_LIMIT")
UITextDef.FACTION_ALREADY_JOINED = GetL10NTextByKey("FACTION_ALREADY_JOINED")
UITextDef.QUEST_BRANCH = GetL10NTextByKey("QUEST_BRANCH")
UITextDef.RECHECKIN_TITLE = GetL10NTextByKey("RECHECKIN_TITLE")
UITextDef.CAPTUREFLAG_QUIT_DUNGEON_TITLE = GetL10NTextByKey("CAPTUREFLAG_QUIT_DUNGEON_TITLE")
UITextDef.TEAM_MAIN_ITEM_NOT_OPEN_UNION = GetL10NTextByKey("TEAM_MAIN_ITEM_NOT_OPEN_UNION")
UITextDef.BATTLEGROUND_FAILED_PLAYERSTATE = GetL10NTextByKey("BATTLEGROUND_FAILED_PLAYERSTATE")
UITextDef.BATTLEGROUND_FAILED_INVALID = GetL10NTextByKey("BATTLEGROUND_FAILED_INVALID")
UITextDef.TRADE_MATERIAL = GetL10NTextByKey("TRADE_MATERIAL")
UITextDef.TEAM_INVITE_REPLY_IN_FIGHT = GetL10NTextByKey("TEAM_INVITE_REPLY_IN_FIGHT")
UITextDef.MMAP_OUTOF_REACH = GetL10NTextByKey("MMAP_OUTOF_REACH")
UITextDef.MMAP_GATHER_POINT = GetL10NTextByKey("MMAP_GATHER_POINT")
UITextDef.SHIP_BACK_AND_REPAIR = GetL10NTextByKey("SHIP_BACK_AND_REPAIR")
UITextDef.SERVER_ERROR = GetL10NTextByKey("SERVER_ERROR")
UITextDef.CHAT_LENGTH_LIMIT = GetL10NTextByKey("CHAT_LENGTH_LIMIT")
UITextDef.SHIP_PART_BUFF_TITLE =
{
    [1] = GetL10NTextByKey("SHIP_PART_BUFF_TITLE1"),
    [2] = GetL10NTextByKey("SHIP_PART_BUFF_TITLE2"),
    [3] = GetL10NTextByKey("SHIP_PART_BUFF_TITLE3"),
    [4] = GetL10NTextByKey("SHIP_PART_BUFF_TITLE4"),
    [5] = GetL10NTextByKey("SHIP_PART_BUFF_TITLE5"),
}
UITextDef.WELFARE_GET_BACK_FAIL_LIMIT = GetL10NTextByKey("WELFARE_GET_BACK_FAIL_LIMIT")
UITextDef.TOWN_PORTAL_NOT_COOL_DOWN = GetL10NTextByKey("TOWN_PORTAL_NOT_COOL_DOWN")
UITextDef.MMAP_ALREADY_IN_DESTINATION = GetL10NTextByKey("MMAP_ALREADY_IN_DESTINATION")
UITextDef.USER_NAME_EMPTY = GetL10NTextByKey("USER_NAME_EMPTY")
UITextDef.USER_NAME_ID_EMPTY = GetL10NTextByKey("USER_NAME_ID_EMPTY")
UITextDef.BATTLEGROUND_ANSWER_DECLINED = GetL10NTextByKey("BATTLEGROUND_ANSWER_DECLINED")
UITextDef.L10N_HIDE_ITEM_RES_SUCCESS = GetL10NTextByKey("L10N_HIDE_ITEM_RES_SUCCESS")
UITextDef.L10N_Buy = GetL10NTextByKey("L10N_Buy")
UITextDef.TEAM_JOIN_TEAM_FULL = GetL10NTextByKey("TEAM_JOIN_TEAM_FULL")
UITextDef.SHIP_CANNOT_SELL_SHIP_TYPE = GetL10NTextByKey("SHIP_CANNOT_SELL_SHIP_TYPE")
UITextDef.MAST_BROKEN_TIPS = GetL10NTextByKey("MAST_BROKEN_TIPS")
UITextDef.WELFARE_GET_BACK_DIALOG_MESSAGE_NORMAL = GetL10NTextByKey("WELFARE_GET_BACK_DIALOG_MESSAGE_NORMAL")
UITextDef.L10N_BACKPACK_FULL_TO_REPLACE_EQUIP = GetL10NTextByKey("L10N_BACKPACK_FULL_TO_REPLACE_EQUIP")
UITextDef.QUEST_ABORT_DESC_SHARED = GetL10NTextByKey("QUEST_ABORT_DESC_SHARED")
UITextDef.TRADE_GAIN = GetL10NTextByKey("TRADE_GAIN")
UITextDef.BATTLEGROUND_FAILED_PLAYDURABILITY = GetL10NTextByKey("BATTLEGROUND_FAILED_PLAYDURABILITY")
UITextDef.SOCIETY_EXPLORER_QUIT_DUNGEON_TITLE = GetL10NTextByKey("SOCIETY_EXPLORER_QUIT_DUNGEON_TITLE")
UITextDef.SCHEDULE_FAIL_TEAM_MEMBER = GetL10NTextByKey("SCHEDULE_FAIL_TEAM_MEMBER")
UITextDef.QUEST_FAILURE_DESC = GetL10NTextByKey("QUEST_FAILURE_DESC")
UITextDef.ASSOCIATION_REFRESH_SUCCESS = GetL10NTextByKey("ASSOCIATION_REFRESH_SUCCESS")
UITextDef.FRIEND_OFFLINE = GetL10NTextByKey("FRIEND_OFFLINE")
UITextDef.SCHEDULE_NOT_START = GetL10NTextByKey("SCHEDULE_NOT_START")
UITextDef.TEAM_APPLY_JION = GetL10NTextByKey("TEAM_APPLY_JION")
UITextDef.ACTIVITY_GUIDE_ACTIVITY_FINISHED = GetL10NTextByKey("ACTIVITY_GUIDE_ACTIVITY_FINISHED")
UITextDef.CHAT_OFFLINE_PLAYER = GetL10NTextByKey("CHAT_OFFLINE_PLAYER")
UITextDef.SHIP_MOD_PART =
{
    [1] = GetL10NTextByKey("SHIP_MOD_PART1"),
    [2] = GetL10NTextByKey("SHIP_MOD_PART2"),
    [3] = GetL10NTextByKey("SHIP_MOD_PART3"),
    [4] = GetL10NTextByKey("SHIP_MOD_PART4"),
    [5] = GetL10NTextByKey("SHIP_MOD_PART5"),
}
UITextDef.ASSOCIATION_REFRESH_TIP = GetL10NTextByKey("ASSOCIATION_REFRESH_TIP")
UITextDef.SCHEDULE_FAIL_NOT_START = GetL10NTextByKey("SCHEDULE_FAIL_NOT_START")
UITextDef.SHIP_BUY_POS_SUCCESS = GetL10NTextByKey("SHIP_BUY_POS_SUCCESS")
UITextDef.SHIP_ADD_SUPPLY_FAILED_NOT_FLAG_SHIP = GetL10NTextByKey("SHIP_ADD_SUPPLY_FAILED_NOT_FLAG_SHIP")
UITextDef.TEAM_LOCKED = GetL10NTextByKey("TEAM_LOCKED")
UITextDef.SCHEDULE_HUMAN_LEVEL_NOT_ENOUGH = GetL10NTextByKey("SCHEDULE_HUMAN_LEVEL_NOT_ENOUGH")
UITextDef.FACTION_POINT_ADD = GetL10NTextByKey("FACTION_POINT_ADD")
UITextDef.L10N_SELECT_EQUIP = GetL10NTextByKey("L10N_SELECT_EQUIP")
UITextDef.COMPLETE_QUEST = GetL10NTextByKey("COMPLETE_QUEST")
UITextDef.PROVOCATIVE_QUIT_DUNGEON_MESSAGE = GetL10NTextByKey("PROVOCATIVE_QUIT_DUNGEON_MESSAGE")
UITextDef.SHIP_SUPPLY_IS_SUFFICIENT = GetL10NTextByKey("SHIP_SUPPLY_IS_SUFFICIENT")
UITextDef.SCHEDULE_HUMAN_LEVEL_CONDITON = GetL10NTextByKey("SCHEDULE_HUMAN_LEVEL_CONDITON")
UITextDef.ARENA_ALIVE_QUIT_DUNGEON_MESSAGE = GetL10NTextByKey("ARENA_ALIVE_QUIT_DUNGEON_MESSAGE")
UITextDef.TEAM_APPLYFOR_TOO_OFTEN = GetL10NTextByKey("TEAM_APPLYFOR_TOO_OFTEN")
UITextDef.MINIGAME_CLICK_ANY_WHERE = GetL10NTextByKey("MINIGAME_CLICK_ANY_WHERE")
UITextDef.RECEIVE_DAY_COUNT = GetL10NTextByKey("RECEIVE_DAY_COUNT")
UITextDef.QUICK_SESSION_TITLE = GetL10NTextByKey("QUICK_SESSION_TITLE")
UITextDef.L10N_COMMA = GetL10NTextByKey("L10N_COMMA")
UITextDef.ASSOCIATION_REFRESH_FAILURE = GetL10NTextByKey("ASSOCIATION_REFRESH_FAILURE")
UITextDef.DISCONNECT_SERVER_FULL = GetL10NTextByKey("DISCONNECT_SERVER_FULL")
UITextDef.AUTO_ROAD_PLAYER = GetL10NTextByKey("AUTO_ROAD_PLAYER")
UITextDef.CAPTUREFLAG_QUIT_DUNGEON_MESSAGE = GetL10NTextByKey("CAPTUREFLAG_QUIT_DUNGEON_MESSAGE")
UITextDef.ARENA_QUIT_DUNGEON_TITLE = GetL10NTextByKey("ARENA_QUIT_DUNGEON_TITLE")
UITextDef.ARENA_TUTORIAL_FORBID_QUIT = GetL10NTextByKey("ARENA_TUTORIAL_FORBID_QUIT")
UITextDef.SCHEDULE_FAIL_NOT_ENOUGH_SHIP_GRADE = GetL10NTextByKey("SCHEDULE_FAIL_NOT_ENOUGH_SHIP_GRADE")
UITextDef.GUIDE_PLAYER_NAME_SELF = GetL10NTextByKey("GUIDE_PLAYER_NAME_SELF")
UITextDef.FACTION_POINT_SUB = GetL10NTextByKey("FACTION_POINT_SUB")
UITextDef.TEAM_INVITE_INVALID_TEAM = GetL10NTextByKey("TEAM_INVITE_INVALID_TEAM")
UITextDef.BATTLE_WAIT_GAME_START = GetL10NTextByKey("BATTLE_WAIT_GAME_START")
UITextDef.L10N_NOT_HIDE_ITEM_RES_SUCCESS = GetL10NTextByKey("L10N_NOT_HIDE_ITEM_RES_SUCCESS")
UITextDef.L10N_SHARED = GetL10NTextByKey("L10N_SHARED")
UITextDef.CAMERA_SHOT_SHOT = GetL10NTextByKey("CAMERA_SHOT_SHOT")
UITextDef.UI_PVP_TITLE_NAME = GetL10NTextByKey("UI_PVP_TITLE_NAME")
UITextDef.FACTION_POINT_RESET = GetL10NTextByKey("FACTION_POINT_RESET")
UITextDef.L10N_LOST_ITEM_CHAT = GetL10NTextByKey("L10N_LOST_ITEM_CHAT")
UITextDef.TRADE_REACH_MAX = GetL10NTextByKey("TRADE_REACH_MAX")
UITextDef.L10N_REPLACE_MESSAGE = GetL10NTextByKey("L10N_REPLACE_MESSAGE")
UITextDef.COMMAND = GetL10NTextByKey("COMMAND")
UITextDef.BATTLEGROUND_MATCH_CANCEL = GetL10NTextByKey("BATTLEGROUND_MATCH_CANCEL")
UITextDef.FACTION_NAME =
{
    [1] = GetL10NTextByKey("FACTION_NAME1"),
    [2] = GetL10NTextByKey("FACTION_NAME2"),
    [3] = GetL10NTextByKey("FACTION_NAME3"),
}
UITextDef.NOT_ENOUGH_FISH = GetL10NTextByKey("NOT_ENOUGH_FISH")
UITextDef.TOWN_PORTAL_MESSAGE = GetL10NTextByKey("TOWN_PORTAL_MESSAGE")
UITextDef.CANNOT_BUY_BACKPACK_FULL = GetL10NTextByKey("CANNOT_BUY_BACKPACK_FULL")
UITextDef.L10N_RESET_EQUIP = GetL10NTextByKey("L10N_RESET_EQUIP")
UITextDef.YELLOW_ARROW = GetL10NTextByKey("YELLOW_ARROW")
UITextDef.QUEST_COMPLETION = GetL10NTextByKey("QUEST_COMPLETION")
UITextDef.FISHING_SCHEDULE_END = GetL10NTextByKey("FISHING_SCHEDULE_END")
UITextDef.FISHING_ENTERMODE_BACKPACKET_FULL = GetL10NTextByKey("FISHING_ENTERMODE_BACKPACKET_FULL")
UITextDef.FISHING_GOFISHING_BACKPACKET_FULL = GetL10NTextByKey("FISHING_GOFISHING_BACKPACKET_FULL")
UITextDef.BATTLEGROUND_FAILED_SHIPCATEGORY = GetL10NTextByKey("BATTLEGROUND_FAILED_SHIPCATEGORY")
UITextDef.SHIP_ADD_SUPPLY_SUCCESS = GetL10NTextByKey("SHIP_ADD_SUPPLY_SUCCESS")
UITextDef.L10N_EQUIP_NOT_MATCH_GRADE = GetL10NTextByKey("L10N_EQUIP_NOT_MATCH_GRADE")
UITextDef.EMPTY_CONTENT = GetL10NTextByKey("EMPTY_CONTENT")
UITextDef.BATTLEGROUND_FAILED_TEAMSHIPCATEGORY = GetL10NTextByKey("BATTLEGROUND_FAILED_TEAMSHIPCATEGORY")
UITextDef.BATTLE_KILL_TIP = GetL10NTextByKey("BATTLE_KILL_TIP")
UITextDef.ACTIVE_VALUE = GetL10NTextByKey("ACTIVE_VALUE")
UITextDef.WORLD_MAP_VIEW_LV_LIMIT = GetL10NTextByKey("WORLD_MAP_VIEW_LV_LIMIT")
UITextDef.CHECKIN_DAY_NUM = GetL10NTextByKey("CHECKIN_DAY_NUM")
UITextDef.L10N_CHANGE_SHIP_HAS_CARGO_DESC = GetL10NTextByKey("L10N_CHANGE_SHIP_HAS_CARGO_DESC")
UITextDef.L10N_HINT = GetL10NTextByKey("L10N_HINT")
UITextDef.CHAT_CDTIME_LIMIT = GetL10NTextByKey("CHAT_CDTIME_LIMIT")
UITextDef.BATTLEGROUND_FAILED_INTERNALERROR = GetL10NTextByKey("BATTLEGROUND_FAILED_INTERNALERROR")
UITextDef.QUEST_FAILURE_DESC_SHARED = GetL10NTextByKey("QUEST_FAILURE_DESC_SHARED")
UITextDef.JSONPVE_QUIT_DUNGEON_MESSAGE = GetL10NTextByKey("JSONPVE_QUIT_DUNGEON_MESSAGE")
UITextDef.ACCEPT_SUB_QUEST = GetL10NTextByKey("ACCEPT_SUB_QUEST")
UITextDef.QUEST_COMPLETE_DESC = GetL10NTextByKey("QUEST_COMPLETE_DESC")
UITextDef.BATTLEGROUND_FAILED_PLAYERLEVEL = GetL10NTextByKey("BATTLEGROUND_FAILED_PLAYERLEVEL")
UITextDef.BATTLEGROUND_FAILED_SHIPGRADE = GetL10NTextByKey("BATTLEGROUND_FAILED_SHIPGRADE")
UITextDef.L10N_BACKPACK_FULL_TO_RESET_EQUIP = GetL10NTextByKey("L10N_BACKPACK_FULL_TO_RESET_EQUIP")
UITextDef.FACTION_QUIT_DUNGEON_MESSAGE = GetL10NTextByKey("FACTION_QUIT_DUNGEON_MESSAGE")
UITextDef.UPDATE_QUEST_PROGRESS = GetL10NTextByKey("UPDATE_QUEST_PROGRESS")
UITextDef.FRIEND_ALREADY_BLACK = GetL10NTextByKey("FRIEND_ALREADY_BLACK")
UITextDef.ALREADY_IN_HIS_BLACK_LIST = GetL10NTextByKey("ALREADY_IN_HIS_BLACK_LIST")
UITextDef.BATTLEGROUND_FAILED_MEMBERLEVEL = GetL10NTextByKey("BATTLEGROUND_FAILED_MEMBERLEVEL")
UITextDef.FRIEND_FULL_BLACK_LIST = GetL10NTextByKey("FRIEND_FULL_BLACK_LIST")
UITextDef.ACCEPT_QUEST = GetL10NTextByKey("ACCEPT_QUEST")
UITextDef.CHAT_NOT_IN_DUNGEON = GetL10NTextByKey("CHAT_NOT_IN_DUNGEON")
UITextDef.SOCIETY_GUARD_QUIT_DUNGEON_TITLE = GetL10NTextByKey("SOCIETY_GUARD_QUIT_DUNGEON_TITLE")
UITextDef.TEAM_JOIN_IN_FIGHT = GetL10NTextByKey("TEAM_JOIN_IN_FIGHT")

UITextDef.DONATE_HEART_SUCCESS = GetL10NTextByKey("DONATE_HEART_SUCCESS")
UITextDef.CANNOT_DONATE_SELF = GetL10NTextByKey("CANNOT_DONATE_SELF")
UITextDef.TARGET_IS_NOT_FRIEND = GetL10NTextByKey("TARGET_IS_NOT_FRIEND")
UITextDef.ALREADY_DONATED = GetL10NTextByKey("ALREADY_DONATED")
UITextDef.FRIEND_HEART_UPLIMIT = GetL10NTextByKey("FRIEND_HEART_UPLIMIT")
UITextDef.FRIEND_HEART_OUTDATE = GetL10NTextByKey("FRIEND_HEART_OUTDATE")
UITextDef.FRIEND_HEART_RECEIVED = GetL10NTextByKey("FRIEND_HEART_RECEIVED")
UITextDef.RECEIVE_HEART_SUCCESS = GetL10NTextByKey("RECEIVE_HEART_SUCCESS")
UITextDef.REPEAT_HEART_REWARDBOX_ID = GetL10NTextByKey("REPEAT_HEART_REWARDBOX_ID")
UITextDef.REWARDBOX_CONDITION_UNREACH = GetL10NTextByKey("REWARDBOX_CONDITION_UNREACH")
UITextDef.GET_HERAT_REWAET_SUCCESS = GetL10NTextByKey("GET_HERAT_REWAET_SUCCESS")
UITextDef.DONATE_OFFLINE_FORBID = GetL10NTextByKey("DONATE_OFFLINE_FORBID")
UITextDef.HAVE_NO_RECEIVABLE_HEART = GetL10NTextByKey("HAVE_NO_RECEIVABLE_HEART")
UITextDef.HAVE_NO_APPLICATION = GetL10NTextByKey("HAVE_NO_APPLICATION")

UITextDef.COMMAND_TIPS =
{
    [1] = GetL10NTextByKey("COMMAND_TIPS1"),
    [2] = GetL10NTextByKey("COMMAND_TIPS2"),
    [3] = GetL10NTextByKey("COMMAND_TIPS3"),
}
UITextDef.BATTLEGROUND_FAILED_PLAYERSCENE = GetL10NTextByKey("BATTLEGROUND_FAILED_PLAYERSCENE")
UITextDef.L10N_EQUIP_NOT_MATCH_CATEGORY = GetL10NTextByKey("L10N_EQUIP_NOT_MATCH_CATEGORY")
UITextDef.CANCEL_QUEST_DIALOG = GetL10NTextByKey("CANCEL_QUEST_DIALOG")
UITextDef.MATCH_BEGIN = GetL10NTextByKey("MATCH_BEGIN")
UITextDef.SMUGGLE_QUIT_DUNGEON_MESSAGE = GetL10NTextByKey("SMUGGLE_QUIT_DUNGEON_MESSAGE")
UITextDef.INVALID_GOODS_COUNT = GetL10NTextByKey("INVALID_GOODS_COUNT")
UITextDef.FISH_EXCHANGE_MAX = GetL10NTextByKey("FISH_EXCHANGE_MAX")
UITextDef.FISHING_MOVE = GetL10NTextByKey("FISHING_MOVE")
UITextDef.BATTLEGROUND_FAILED_FORBIDDENBUFF = GetL10NTextByKey("BATTLEGROUND_FAILED_FORBIDDENBUFF")
UITextDef.GO_TO_SEA_FAIL_NOT_ENOUGH_SUPPLY = GetL10NTextByKey("GO_TO_SEA_FAIL_NOT_ENOUGH_SUPPLY")
UITextDef.L10N_GAINED_GOLD = GetL10NTextByKey("L10N_GAINED_GOLD")
UITextDef.BATTLEGROUND_FAILED_MEMBERDURABILITY = GetL10NTextByKey("BATTLEGROUND_FAILED_MEMBERDURABILITY")
UITextDef.TRADE_BUY = GetL10NTextByKey("TRADE_BUY")
UITextDef.BATTLEGROUND_ANSWER_DISCONNECTED = GetL10NTextByKey("BATTLEGROUND_ANSWER_DISCONNECTED")
UITextDef.TEAM_JOIN_IN_BLACK_LIST = GetL10NTextByKey("TEAM_JOIN_IN_BLACK_LIST")
UITextDef.QUEST_ABORT_OP = GetL10NTextByKey("QUEST_ABORT_OP")
UITextDef.SHIP_CHANGE_FAILED_CURRENT_SHIP = GetL10NTextByKey("SHIP_CHANGE_FAILED_CURRENT_SHIP")
UITextDef.SHIP_POS_MAX = GetL10NTextByKey("SHIP_POS_MAX")
UITextDef.QUEST_ACCEPT_DESC_SHARED = GetL10NTextByKey("QUEST_ACCEPT_DESC_SHARED")
UITextDef.L10N_CONSUMABLE_DELETE = GetL10NTextByKey("L10N_CONSUMABLE_DELETE")
UITextDef.SCHEDULE_SHIP_GRADE_CONDITON = GetL10NTextByKey("SCHEDULE_SHIP_GRADE_CONDITON")
UITextDef.SHOOT_INFO =
{
    [1] = GetL10NTextByKey("SHOOT_INFO1"),
    [2] = GetL10NTextByKey("SHOOT_INFO2"),
    [3] = GetL10NTextByKey("SHOOT_INFO3"),
    [4] = GetL10NTextByKey("SHOOT_INFO4"),
    [5] = GetL10NTextByKey("SHOOT_INFO5"),
    [6] = GetL10NTextByKey("SHOOT_INFO6"),
    [7] = GetL10NTextByKey("SHOOT_INFO7"),
}
UITextDef.TOWN_PORTAL_IN_BIG_PORT = GetL10NTextByKey("TOWN_PORTAL_IN_BIG_PORT")
UITextDef.FRIEND_ADD_OTHER_FULL = GetL10NTextByKey("FRIEND_ADD_OTHER_FULL")
UITextDef.L10N_REPLACE_EQUIP = GetL10NTextByKey("L10N_REPLACE_EQUIP")
UITextDef.DUNGEON_NOT_READY = GetL10NTextByKey("DUNGEON_NOT_READY")
UITextDef.ACTIVITY_GUIDE_INFINITE_COUNT = GetL10NTextByKey("ACTIVITY_GUIDE_INFINITE_COUNT")
UITextDef.L10N_CHANGE_SHIP_HAS_CARGO_TITLE = GetL10NTextByKey("L10N_CHANGE_SHIP_HAS_CARGO_TITLE")
UITextDef.PASSIVE_SKILL = GetL10NTextByKey("PASSIVE_SKILL")
UITextDef.JSONPVE_QUIT_DUNGEON_TITLE = GetL10NTextByKey("JSONPVE_QUIT_DUNGEON_TITLE")
UITextDef.TOWN_PORTAL_SCENE_INVALID = GetL10NTextByKey("TOWN_PORTAL_SCENE_INVALID")
UITextDef.ESCORT_QUIT_DUNGEON_TITLE = GetL10NTextByKey("ESCORT_QUIT_DUNGEON_TITLE")
UITextDef.ACTIVE_COUNT = GetL10NTextByKey("ACTIVE_COUNT")
UITextDef.MMAP_OUTOF_REACH_LAND = GetL10NTextByKey("MMAP_OUTOF_REACH_LAND")
UITextDef.WELFARE_TREASURE_LAST_FREE_TIME = GetL10NTextByKey("WELFARE_TREASURE_LAST_FREE_TIME")
UITextDef.CHAT_CDTIME_LIMIT_TIME = GetL10NTextByKey("CHAT_CDTIME_LIMIT_TIME")
UITextDef.SOCIETY_EXPLORER_QUIT_DUNGEON_MESSAGE = GetL10NTextByKey("SOCIETY_EXPLORER_QUIT_DUNGEON_MESSAGE")
UITextDef.FLAG_SHIP_CANNOT_SELL = GetL10NTextByKey("FLAG_SHIP_CANNOT_SELL")
UITextDef.TRADE_UNIT = GetL10NTextByKey("TRADE_UNIT")
UITextDef.ABORT_NAV_MOVE = GetL10NTextByKey("ABORT_NAV_MOVE")
UITextDef.WELFARE_TREASURE_MAX_TIME = GetL10NTextByKey("WELFARE_TREASURE_MAX_TIME")
UITextDef.SOCIETY_PRIVATEER_QUIT_DUNGEON_TITLE = GetL10NTextByKey("SOCIETY_PRIVATEER_QUIT_DUNGEON_TITLE")
UITextDef.MINIGAME_SKIP_CONFIRM_TITLE = GetL10NTextByKey("MINIGAME_SKIP_CONFIRM_TITLE")
UITextDef.CHAT_SILVER_LIMIT = GetL10NTextByKey("CHAT_SILVER_LIMIT")
UITextDef.WORLDBOSS_QUIT_DUNGEON_TITLE = GetL10NTextByKey("WORLDBOSS_QUIT_DUNGEON_TITLE")
UITextDef.GUILDBOSS_QUIT_DUNGEON_TITLE = GetL10NTextByKey("GUILDBOSS_QUIT_DUNGEON_TITLE")
UITextDef.ACTIVITYPVE_QUIT_DUNGEON_TITLE = GetL10NTextByKey("ACTIVITYPVE_QUIT_DUNGEON_TITLE")
UITextDef.WORLDBOSS_QUIT_DUNGEON_MESSAGE = GetL10NTextByKey("WORLDBOSS_QUIT_DUNGEON_MESSAGE")
UITextDef.GUILDBOSS_QUIT_DUNGEON_MESSAGE = GetL10NTextByKey("GUILDBOSS_QUIT_DUNGEON_MESSAGE")
UITextDef.ACTIVITYPVE_QUIT_DUNGEON_MESSAGE = GetL10NTextByKey("ACTIVITYPVE_QUIT_DUNGEON_MESSAGE")
UITextDef.COMMON_STRING = GetL10NTextByKey("COMMON_STRING")
UITextDef.COMMON_CURCOUNT_MAXCOUNT = GetL10NTextByKey("COMMON_CURCOUNT_MAXCOUNT")
UITextDef.COMMON_PLAYER_LEVEL = GetL10NTextByKey("COMMON_PLAYER_LEVEL")
UITextDef.COMMON_ONLINE = GetL10NTextByKey("COMMON_ONLINE")
UITextDef.COMMON_DATA_ERROR = GetL10NTextByKey("COMMON_DATA_ERROR")
UITextDef.COMMON_LEVEL_1 = GetL10NTextByKey("COMMON_LEVEL_1")
UITextDef.COMMON_RETURN = GetL10NTextByKey("COMMON_RETURN")
UITextDef.COMMON_CONTINUE = GetL10NTextByKey("COMMON_CONTINUE")
-- UITextDef.GUILD_REQUEST_NOREACH_CONDITION_TOAST = GetL10NTextByKey("GUILD_REQUEST_NOREACH_CONDITION_TOAST")
-- UITextDef.GUILD_DUTY_NOPREVILEGE_TOTAST = GetL10NTextByKey("GUILD_DUTY_NOPREVILEGE_TOTAST")
-- UITextDef.GUILD_FULLMEMBER_TOAST = GetL10NTextByKey("GUILD_FULLMEMBER_TOAST")
-- UITextDef.GUILD_REQUESTED_TOAST  = GetL10NTextByKey("GUILD_REQUESTED_TOAST")
-- UITextDef.GUILD_JOINCD_TOAST = GetL10NTextByKey("GUILD_JOINCD_TOAST")
-- UITextDef.GUILD_BUY_MEMBER_MAX_TOAST = GetL10NTextByKey("GUILD_BUY_MEMBER_MAX_TOAST")
-- UITextDef.GUILD_BUY_MEMBER_NOCURRNCY_TOAST = GetL10NTextByKey("GUILD_BUY_MEMBER_NOCURRNCY_TOAST")
-- UITextDef.GUILD_DISSOLVE_TRANSFERING_TOAST = GetL10NTextByKey("GUILD_DISSOLVE_TRANSFERING_TOAST")
-- UITextDef.GUILD_DISSOLVING_CANNOT_ANONOUCEMENT_TOAST = GetL10NTextByKey("GUILD_DISSOLVING_CANNOT_ANONOUCEMENT_TOAST")
-- UITextDef.GUILD_ANNOUNCEMENT_ILLEGAL_TOAST = GetL10NTextByKey("GUILD_ANNOUNCEMENT_ILLEGAL_TOAST")
-- UITextDef.GUILD_CREATE_NOCURRENCY_TOTAST = GetL10NTextByKey("GUILD_CREATE_NOCURRENCY_TOTAST")
-- UITextDef.GUILD_NAME_ALL_NUMBER_TOTAST   = GetL10NTextByKey("GUILD_NAME_ALL_NUMBER_TOTAST")
-- UITextDef.GUILD_NAME_ILLEGAL_TOTAST      = GetL10NTextByKey("GUILD_NAME_ILLEGAL_TOTAST")
-- UITextDef.GUILD_NAME_EMPTY_TOTAST        = GetL10NTextByKey("GUILD_NAME_EMPTY_TOTAST")
-- UITextDef.GUILD_NAME_LENGTH_TOTAST       = GetL10NTextByKey("GUILD_NAME_LENGTH_TOTAST")
-- UITextDef.GUILD_JOIN_MIN_LEVEL_TOTAST    = GetL10NTextByKey("GUILD_JOIN_MIN_LEVEL_TOTAST")
-- UITextDef.GUILD_NAME_EXISTED_TOTAST      = GetL10NTextByKey("GUILD_NAME_EXISTED_TOTAST")
-- UITextDef.GUILD_COUNT_FULL_TOTAST        = GetL10NTextByKey("GUILD_COUNT_FULL_TOTAST")
-- UITextDef.GUILD_NOT_EXIST_TOTAST         = GetL10NTextByKey("GUILD_NOT_EXIST_TOTAST")
-- UITextDef.GUILD_ALREADY_JOIN_TOTAST      = GetL10NTextByKey("GUILD_ALREADY_JOIN_TOTAST")
-- UITextDef.GUILD_NOT_HAS_AUTO_JOIN_TOTAST = GetL10NTextByKey("GUILD_NOT_HAS_AUTO_JOIN_TOTAST")
-- UITextDef.GUILD_NOT_JOIN_TOTAST          = GetL10NTextByKey("GUILD_NOT_JOIN_TOTAST")
-- UITextDef.GUILD_INVALIDE_JOIN_REQUESTER_TOTAST = GetL10NTextByKey("GUILD_INVALIDE_JOIN_REQUESTER_TOTAST")
-- UITextDef.GUILD_ANNOUNCEMENT_LENGTH_TOAST= GetL10NTextByKey("GUILD_ANNOUNCEMENT_LENGTH_TOAST")
-- UITextDef.GUILD_INVITE_PLAYER_OFFLINE_TOTAST = GetL10NTextByKey("GUILD_INVITE_PLAYER_OFFLINE_TOTAST")
-- UITextDef.GUILD_INVALID_INVITE_TOTAST    = GetL10NTextByKey("GUILD_INVALID_INVITE_TOTAST")
-- UITextDef.GUILD_DUTY_MEMBER_FULL_TOTAST  = GetL10NTextByKey("GUILD_DUTY_MEMBER_FULL_TOTAST")
-- UITextDef.GUILD_KICK_MEMBER_COUNT_FULL_TOTAST = GetL10NTextByKey("GUILD_KICK_MEMBER_COUNT_FULL_TOTAST")
-- UITextDef.GUILD_PRESIDENT_TRANSFER_TIME_TOTAST= GetL10NTextByKey("GUILD_PRESIDENT_TRANSFER_TIME_TOTAST")
-- UITextDef.GUILD_PRESIDENT_CAN_NOT_LEAVE_TOTAST= GetL10NTextByKey("GUILD_PRESIDENT_CAN_NOT_LEAVE_TOTAST")
-- UITextDef.GUILD_BUY_MEMBER_COUNT_INVALID_TOTAST= GetL10NTextByKey("GUILD_BUY_MEMBER_COUNT_INVALID_TOTAST")
-- UITextDef.GUILD_BUY_MEMBER_COUNT_FULL_TOTAST  = GetL10NTextByKey("GUILD_BUY_MEMBER_COUNT_FULL_TOTAST")
-- UITextDef.GUILD_JOINCGUILD_JOINCD_TOASTD_TOAST= GetL10NTextByKey("GUILD_JOINCGUILD_JOINCD_TOASTD_TOAST")
-- UITextDef.GUILD_DISSOLVE_TIME_TOTAST = GetL10NTextByKey("GUILD_DISSOLVE_TIME_TOTAST")
-- UITextDef.GUILD_NOT_DISSOLVE_TOTAST  = GetL10NTextByKey("GUILD_NOT_DISSOLVE_TOTAST")
-- UITextDef.GUILD_PRESIDENT_NOT_TRANSFER_TOTAST  = GetL10NTextByKey("GUILD_PRESIDENT_NOT_TRANSFER_TOTAST")
-- UITextDef.CHAT_GUILD_FORBID_CHAT_TOTAST  = GetL10NTextByKey("CHAT_GUILD_FORBID_CHAT_TOTAST")
-- UITextDef.GUILD_INVITE_IN_DUNGEON_TOTAST  = GetL10NTextByKey("GUILD_INVITE_IN_DUNGEON_TOTAST")


UITextDef.BATTLE_RESULT_TITLE_FRIEND = GetL10NTextByKey("UI_STATIC_BATTLE_RESULT_TITLE_FRIEND")
UITextDef.BATTLE_RESULT_TITLE_ENEMY = GetL10NTextByKey("UI_STATIC_BATTLE_RESULT_TITLE_ENEMY")
UITextDef.BATTLE_RESULT_TITLE_TOWER = GetL10NTextByKey("UI_STATIC_BATTLE_RESULT_TITLE_TOWER")
UITextDef.BATTLE_RESULT_TITLE_FLAG = GetL10NTextByKey("UI_STATIC_BATTLE_RESULT_TITLE_FLAG")
UITextDef.BATTLE_RESULT_TITLE_KILL = GetL10NTextByKey("UI_STATIC_BATTLE_RESULT_TITLE_KILL")
UITextDef.BATTLE_RESULT_TITLE_DIE = GetL10NTextByKey("UI_STATIC_BATTLE_RESULT_TITLE_DIE")
UITextDef.BATTLE_RESULT_TITLE_DAMAGE = GetL10NTextByKey("UI_STATIC_BATTLE_RESULT_TITLE_DAMAGE")
UITextDef.BATTLE_RESULT_TITLE_CURE = GetL10NTextByKey("UI_STATIC_BATTLE_RESULT_TITLE_CURE")

UITextDef.BATTLE_RESULT_DETAIL_CURE = GetL10NTextByKey("UI_FORMAT_BATTLE_RESULT_DETAIL_CURE")
UITextDef.BATTLE_RESULT_DETAIL_MAIN_CANNON = GetL10NTextByKey("UI_FORMAT_BATTLE_RESULT_DETAIL_MAIN_CANNON")
UITextDef.BATTLE_RESULT_DETAIL_HIT_TARGET = GetL10NTextByKey("UI_FORMAT_BATTLE_RESULT_DETAIL_HIT_TARGET")
UITextDef.BATTLE_RESULT_DETAIL_SECD_CANNON = GetL10NTextByKey("UI_FORMAT_BATTLE_RESULT_DETAIL_SECD_CANNON")
UITextDef.BATTLE_RESULT_DETAIL_TORPEDO = GetL10NTextByKey("UI_FORMAT_BATTLE_RESULT_DETAIL_TORPEDO")
UITextDef.BATTLE_RESULT_DETAIL_FIRE = GetL10NTextByKey("UI_FORMAT_BATTLE_RESULT_DETAIL_FIRE")
UITextDef.BATTLE_RESULT_DETAIL_LEAK = GetL10NTextByKey("UI_FORMAT_BATTLE_RESULT_DETAIL_LEAK")
UITextDef.BATTLE_RESULT_DETAIL_KILL = GetL10NTextByKey("UI_FORMAT_BATTLE_RESULT_DETAIL_KILL")
UITextDef.BATTLE_RESULT_DETAIL_SAIL = GetL10NTextByKey("UI_FORMAT_BATTLE_RESULT_DETAIL_SAIL")
UITextDef.BATTLE_RESULT_DETAIL_TOOK_MAIN_CANNON = GetL10NTextByKey("UI_FORMAT_BATTLE_DETAIL_TOOK_MAIN_CANNON")
UITextDef.BATTLE_RESULT_DETAIL_TOOK_SECD_CANNON = GetL10NTextByKey("UI_FORMAT_BATTLE_DETAIL_TOOK_SECD_CANNON")
UITextDef.BATTLE_RESULT_DETAIL_TOOK_TORPEDO = GetL10NTextByKey("UI_FORMAT_BATTLE_DETAIL_TOOK_TORPEDO")
UITextDef.BATTLE_RESULT_DETAIL_TOOK_FIRE = GetL10NTextByKey("UI_FORMAT_BATTLE_DETAIL_TOOK_FIRE")
UITextDef.BATTLE_RESULT_DETAIL_TOOK_LEAK = GetL10NTextByKey("UI_FORMAT_BATTLE_DETAIL_TOOK_LEAK")

UITextDef.BATTLE_RESULT_FLAG_DATA = GetL10NTextByKey("UI_FORMAT_BATTLE_RESULT_FLAG_DATA")

UITextDef.WORLDBOSS_LEADERBOARD_RANK = GetL10NTextByKey("UI_WORLDBOSS_LEADERBOARD_RANK")
UITextDef.WORLDBOSS_LEADERBOARD_RANK_DEFAULT = GetL10NTextByKey("UI_WORLDBOSS_LEADERBOARD_RANK_DEFAULT")
UITextDef.WORLDBOSS_LEADERBOARD_DAMAGE = GetL10NTextByKey("UI_WORLDBOSS_LEADERBOARD_DAMAGE")
UITextDef.WORLDBOSS_MAIN_TIMES = GetL10NTextByKey("UI_WORLDBOSS_MAIN_TIMES")
UITextDef.WORLDBOSS_SINGLE_MATCH_TITLE = GetL10NTextByKey("WORLDBOSS_SINGLE_MATCH_TITLE")
UITextDef.WORLDBOSS_TEAM_MATCH_TITLE = GetL10NTextByKey("WORLDBOSS_TEAM_MATCH_TITLE")


UITextDef.REFRESH_INTERVAL_TOAST = GetL10NTextByKey("REFRESH_INTERVAL_TOAST")
UITextDef.EXEC_COMMAND_SECCUSS = GetL10NTextByKey("EXEC_COMMAND_SECCUSS")

UITextDef.AUTO_PROGRESS_TIP = GetL10NTextByKey("UI_PROGRESS_TIP")
UITextDef.AUTO_RND_PROGRESS_TIP = GetL10NTextByKey("UI_RND_PROGRESS_TIP")

UITextDef.FFA_INFO_LEFT_TIME = GetL10NTextByKey("FFA_INFO_LEFT_TIME")
UITextDef.FFA_INFO_LEFT_PLAYER = GetL10NTextByKey("FFA_INFO_LEFT_PLAYER")
UITextDef.FFA_PARACHUTING_SPEED = GetL10NTextByKey("FFA_PARACHUTING_SPEED")
UITextDef.FFA_PARACHUTING_PLAYERCOUNT = GetL10NTextByKey("FFA_PARACHUTING_PLAYERCOUNT")

UITextDef.FFA_PACKAGE_NOT_FOUND_WEAPON = GetL10NTextByKey("FFA_PACKAGE_NOT_FOUND_WEAPON")
UITextDef.FFA_ATTACHMENT_NOT_MATCH = GetL10NTextByKey("FFA_ATTACHMENT_NOT_MATCH")

UITextDef.FFA_HUMAN_INVENTORY_FULL = GetL10NTextByKey("FFA_HUMAN_INVENTORY_FULL")
UITextDef.FFA_SHIP_INVENTORY_FULL = GetL10NTextByKey("FFA_SHIP_INVENTORY_FULL")
UITextDef.FFA_MATERAIL_INVENTORY_FULL = GetL10NTextByKey("FFA_MATERAIL_INVENTORY_FULL")
UITextDef.FFA_INVENTORY_CAPACITY_NOT_ENOUGHT = GetL10NTextByKey("FFA_INVENTORY_CAPACITY_NOT_ENOUGHT")
UITextDef.FFA_ITEM_HAS_ALREADY_PICKED = GetL10NTextByKey("FFA_ITEM_HAS_ALREADY_PICKED")

UITextDef.FFA_MATERIALS_NOT_ENOUGH = GetL10NTextByKey("FFA_MATERIALS_NOT_ENOUGH")
UITextDef.FFA_KEY_ITEMS_NOT_ENOUGH = GetL10NTextByKey("FFA_KEY_ITEMS_NOT_ENOUGH")
UITextDef.FFA_PREREQUISITE_ITEMS_NOT_ENOUGH = GetL10NTextByKey("FFA_PREREQUISITE_ITEMS_NOT_ENOUGH")
UITextDef.FFA_ITEM_TYPE_CANNOT_BUILD = GetL10NTextByKey("FFA_ITEM_TYPE_CANNOT_BUILD")
UITextDef.FFA_INACCEPTABLE_PLAYER_SHIP_BUILDING_LEVEL = GetL10NTextByKey("FFA_INACCEPTABLE_PLAYER_SHIP_BUILDING_LEVEL")
UITextDef.FFA_SHIP_BUILDING_NEED_LOW_LEVEL = GetL10NTextByKey("FFA_SHIP_BUILDING_NEED_LOW_LEVEL")
UITextDef.FFA_NOT_COMPATIBLE = GetL10NTextByKey("FFA_NOT_COMPATIBLE")
UITextDef.UI_STATIC_FFA_RESERVE_ITEM_BUILD = GetL10NTextByKey("UI_STATIC_FFA_RESERVE_ITEM_BUILD")
UITextDef.UI_STATIC_FFA_CANCEL_RESERVE_ITEM_BUILD = GetL10NTextByKey("UI_STATIC_FFA_CANCEL_RESERVE_ITEM_BUILD")

UITextDef.CANNOT_START_PROGRESSBAR = GetL10NTextByKey("CANNOT_START_PROGRESSBAR")

UITextDef.UI_HOMELAND_MODE_NORMAL = GetL10NTextByKey("UI_HOMELAND_MODE_NORMAL")
UITextDef.UI_HOMELAND_MODE_BUILD = GetL10NTextByKey("UI_HOMELAND_MODE_BUILD")
UITextDef.LANDMARK_NAME_FORMAT = GetL10NTextByKey("LANDMARK_NAME_FORMAT")
UITextDef.DOCK_FUNCTION_DESC = GetL10NTextByKey("DOCK_FUNCTION_DESC")
UITextDef.UI_HOMELAND_BUY_BLOCK = GetL10NTextByKey("UI_HOMELAND_BUY_BLOCK")
UITextDef.UI_HOMELAND_PLACE_BUILDING = GetL10NTextByKey("UI_HOMELAND_PLACE_BUILDING")
UITextDef.UI_HOMELAND_REMOVE_BUILDING = GetL10NTextByKey("UI_HOMELAND_REMOVE_BUILDING")
UITextDef.UI_LANDMARK_UPGRADE_COUNT_DOWN_MINUTE = GetL10NTextByKey("UI_LANDMARK_UPGRADE_COUNT_DOWN_MINUTE")
UITextDef.UI_LANDMARK_UPGRADE_COUNT_DOWN_SECOND = GetL10NTextByKey("UI_LANDMARK_UPGRADE_COUNT_DOWN_SECOND")
UITextDef.LANDMARK_RESEARCH_BUILDING_GRADE = GetL10NTextByKey("LANDMARK_RESEARCH_BUILDING_GRADE")
UITextDef.UI_HOMELAND_RESEARCH_OPEN = GetL10NTextByKey("UI_HOMELAND_RESEARCH_OPEN")
UITextDef.UI_HOMELAND_RESEARCH_CLOSE = GetL10NTextByKey("UI_HOMELAND_RESEARCH_CLOSE")
UITextDef.HOME_RESEARCH_FAILED_NOT_ENOUGH_CURRENCY = GetL10NTextByKey("HOME_RESEARCH_FAILED_NOT_ENOUGH_CURRENCY")

UITextDef.CONSUMABLE_HP_LIMIT = GetL10NTextByKey("CONSUMABLE_HP_LIMIT")
UITextDef.CONSUMABLE_SHIP_CAN_NOT_USE = GetL10NTextByKey("CONSUMABLE_SHIP_CAN_NOT_USE")
UITextDef.CONSUMABLE_HUMAN_CAN_NOT_USE = GetL10NTextByKey("CONSUMABLE_HUMAN_CAN_NOT_USE")
UITextDef.CONSUMABLE_CRAWL_CAN_NOT_USE = GetL10NTextByKey("CONSUMABLE_CRAWL_CAN_NOT_USE")

UITextDef.UI_INTERACTION_CHANGESHIP = GetL10NTextByKey("UI_INTERACTION_CHANGESHIP")
UITextDef.UI_INTERACTION_CHANGEHUMAN = GetL10NTextByKey("UI_INTERACTION_CHANGEHUMAN")

UITextDef.UI_BACKPACK_EQUIPMENT_ENABLE = GetL10NTextByKey("UI_BACKPACK_EQUIPMENT_ENABLE")
UITextDef.UI_BACKPACK_EQUIPMENT_DISABLE = GetL10NTextByKey("UI_BACKPACK_EQUIPMENT_DISABLE")

UITextDef.UI_STATIC_FFA_BACKPACK_EQUIP = GetL10NTextByKey("UI_STATIC_FFA_BACKPACK_EQUIP")
UITextDef.UI_STATIC_FFA_BACKPACK_CLOTH = GetL10NTextByKey("UI_STATIC_FFA_BACKPACK_CLOTH")
UITextDef.UI_STATIC_FFA_BACKPACK_MATERIAL = GetL10NTextByKey("UI_STATIC_FFA_BACKPACK_MATERIAL")

UITextDef.LOBBY_ITEM_HOLD_LIMIT = GetL10NTextByKey("LOBBY_ITEM_HOLD_LIMIT")

UITextDef.LOBBY_ITEM_FAILED_CANNOT_USE = GetL10NTextByKey("LOBBY_ITEM_FAILED_CANNOT_USE")
UITextDef.LOBBY_ITEM_FAILED_NOT_FOUND = GetL10NTextByKey("LOBBY_ITEM_FAILED_NOT_FOUND")
UITextDef.LOBBY_ITEM_FAILED_CANNOT_SELL = GetL10NTextByKey("LOBBY_ITEM_FAILED_CANNOT_SELL")
UITextDef.LOBBY_ITEM_FAILED_NOT_IN_BACKPACK = GetL10NTextByKey("LOBBY_ITEM_FAILED_NOT_IN_BACKPACK")
UITextDef.LOBBY_ITEM_FAILED_NOT_ENOUGH = GetL10NTextByKey("LOBBY_ITEM_FAILED_NOT_ENOUGH")
UITextDef.LOBBY_ITEM_FAILED_EXPIRED = GetL10NTextByKey("LOBBY_ITEM_FAILED_EXPIRED")
UITextDef.LOBBY_ITEM_FAILED_LEVEL_LIMITED = GetL10NTextByKey("LOBBY_ITEM_FAILED_LEVEL_LIMITED")
UITextDef.LOBBY_ITEM_FAILED_GENDER_NOT_MATCH = GetL10NTextByKey("LOBBY_ITEM_FAILED_GENDER_NOT_MATCH")
UITextDef.LOBBY_ITEM_USE_SUCCESS = GetL10NTextByKey("LOBBY_ITEM_USE_SUCCESS")
UITextDef.LOBBY_ITEM_USE_FAILED = GetL10NTextByKey("LOBBY_ITEM_USE_FAILED")
UITextDef.LOBBY_ITEM_SELL_FAILED = GetL10NTextByKey("LOBBY_ITEM_SELL_FAILED")
UITextDef.LOBBY_ITEM_USE_TOO_MUCH = GetL10NTextByKey("LOBBY_ITEM_USE_TOO_MUCH")
UITextDef.WELFARE_GET_FAIL = GetL10NTextByKey("WELFARE_GET_FAIL")
UITextDef.UPGRADE_MAX_LEVEL = GetL10NTextByKey("UPGRADE_MAX_LEVEL")

UITextDef.SHIP_WEAPON_SLOT_NAME =
{
    [ShipWeaponSlotDef.HEAD] = GetL10NTextByKey("SHIP_WEAPON_SLOT_NAME_HEAD"),
    [ShipWeaponSlotDef.SIDE] = GetL10NTextByKey("SHIP_WEAPON_SLOT_NAME_SIDE"),
    [ShipWeaponSlotDef.DECK] = GetL10NTextByKey("SHIP_WEAPON_SLOT_NAME_DECK")
}

UITextDef.FFA_SHIP_SWITCH_TO_JOYSTICK = GetL10NTextByKey("FFA_SHIP_SWITCH_TO_JOYSTICK")
UITextDef.FFA_SHIP_SWITCH_TO_RUDDER = GetL10NTextByKey("FFA_SHIP_SWITCH_TO_RUDDER")
UITextDef.FAILED_WITH_PLAYER_IN_DYING = GetL10NTextByKey("FAILED_WITH_PLAYER_IN_DYING")
UITextDef.FFA_SELECT_POINT_INVALID = GetL10NTextByKey("FFA_SELECT_POINT_INVALID")
UITextDef.FFA_SELECT_POINT_SUCCESS = GetL10NTextByKey("FFA_SELECT_POINT_SUCCESS")
UITextDef.FFA_SELECT_POINT_ISLOCK = GetL10NTextByKey("FFA_SELECT_POINT_ISLOCK")
UITextDef.FFA_CANCEL_SELECT_POINT_ISLOCK = GetL10NTextByKey("FFA_CANCEL_SELECT_POINT_ISLOCK")
UITextDef.FFA_FUNCTION_NOT_OPEN = GetL10NTextByKey("FFA_FUNCTION_NOT_OPEN")
UITextDef.FFA_OVERTIMER = GetL10NTextByKey("FFA_OVERTIMER")
UITextDef.SELFTIMECALCULATEHELPER_L10N_DAY = GetL10NTextByKey("SELFTIMECALCULATEHELPER_L10N_DAY")
UITextDef.SELFTIMECALCULATEHELPER_L10N_HOUR = GetL10NTextByKey("SELFTIMECALCULATEHELPER_L10N_HOUR")
UITextDef.SELFTIMECALCULATEHELPER_L10N_MIN = GetL10NTextByKey("SELFTIMECALCULATEHELPER_L10N_MIN")

UITextDef.BATTLE_MODE_ONE = GetL10NTextByKey("BATTLE_MODE_ONE")
UITextDef.BATTLE_MODE_TWO = GetL10NTextByKey("BATTLE_MODE_TWO")
UITextDef.BATTLE_MODE_FOUR = GetL10NTextByKey("BATTLE_MODE_FOUR")


UITextDef.MAIL_TIME_SECONDS_AGO = GetL10NTextByKey("MAIL_TIME_SECONDS_AGO")
UITextDef.MAIL_TIME_MINUTES_AGO = GetL10NTextByKey("MAIL_TIME_MINUTES_AGO")
UITextDef.MAIL_TIME_HOURS_AGO = GetL10NTextByKey("MAIL_TIME_HOURS_AGO")
UITextDef.MAIL_TIME_DAYS_AGO = GetL10NTextByKey("MAIL_TIME_DAYS_AGO")
UITextDef.MAIL_OUT_OF_DATE = GetL10NTextByKey("MAIL_OUT_OF_DATE")
UITextDef.MAIL_TIME_SECONDS_REMAINING = GetL10NTextByKey("MAIL_TIME_SECONDS_REMAINING")
UITextDef.MAIL_TIME_MINUTES_REMAINING = GetL10NTextByKey("MAIL_TIME_MINUTES_REMAINING")
UITextDef.MAIL_TIME_HOURS_REMAINING = GetL10NTextByKey("MAIL_TIME_HOURS_REMAINING")
UITextDef.MAIL_TIME_DAYS_REMAINING = GetL10NTextByKey("MAIL_TIME_DAYS_REMAINING")
UITextDef.MAIL_TIME_SECONDS_AGO = GetL10NTextByKey("MAIL_TIME_SECONDS_AGO")
UITextDef.MAIL_BOX_TYPE_SYSTEM = GetL10NTextByKey("MAIL_BOX_TYPE_SYSTEM")
UITextDef.MAIL_BOX_TYPE_FRIEND = GetL10NTextByKey("MAIL_BOX_TYPE_FRIEND")
UITextDef.MAIL_BOX_TYPE_MESSAGE_CENTER = GetL10NTextByKey("MAIL_BOX_TYPE_MESSAGE_CENTER")
UITextDef.MAIL_FRIEND_STATE_IDLE = GetL10NTextByKey("MAIL_FRIEND_STATE_IDLE")
UITextDef.MAIL_FRIEND_STATE_IN_TEAM = GetL10NTextByKey("MAIL_FRIEND_STATE_IN_TEAM")
UITextDef.MAIL_FRIEND_STATE_PLAYING = GetL10NTextByKey("MAIL_FRIEND_STATE_PLAYING")
UITextDef.MAIL_FRIEND_STATE_OFFLINE = GetL10NTextByKey("MAIL_FRIEND_STATE_OFFLINE")
UITextDef.MAIL_FRIEND_STATE_OFFLINE = GetL10NTextByKey("MAIL_FRIEND_STATE_OFFLINE")
UITextDef.MAIL_TEAM_JOIN = GetL10NTextByKey("MAIL_TEAM_JOIN")
UITextDef.MAIL_TEAM_INVITE = GetL10NTextByKey("MAIL_TEAM_INVITE")
UITextDef.MAIL_GET_AND_GIVEBACK = GetL10NTextByKey("MAIL_GET_AND_GIVEBACK")
UITextDef.MAIL_GET_ATTACHMENT = GetL10NTextByKey("MAIL_GET_ATTACHMENT")
UITextDef.MAIL_NO_MAIL_TO_READ = GetL10NTextByKey("MAIL_NO_MAIL_TO_READ")
UITextDef.MAIL_NO_MAIL_ATTACHMENT_TO_GET = GetL10NTextByKey("MAIL_NO_MAIL_ATTACHMENT_TO_GET")
UITextDef.MAIL_NO_MAIL_TO_DELETE = GetL10NTextByKey("MAIL_NO_MAIL_TO_DELETE")
UITextDef.MAIL_VALID_TIME = GetL10NTextByKey("MAIL_VALID_TIME")

UITextDef.UIEQUIPMENTTIPS_ITEM_REMOVED = GetL10NTextByKey("UIEQUIPMENTTIPS_ITEM_REMOVED")

UITextDef.CHAT_LENGTH_LIMITE = GetL10NTextByKey("CHAT_LENGTH_LIMITE")
UITextDef.CHAT_CLICK_TO_CHAT = GetL10NTextByKey("CHAT_CLICK_TO_CHAT")
UITextDef.COPY_SUCCEED = GetL10NTextByKey("COPY_SUCCEED")
UITextDef.MAIL_DATA_ERROR = GetL10NTextByKey("MAIL_DATA_ERROR")
UITextDef.CHAT_TIME_REMINE = GetL10NTextByKey("CHAT_TIME_REMINE")

UITextDef.SEASON_ALREADY_GET_DAILYAWARD = GetL10NTextByKey("SEASON_ALREADY_GET_DAILYAWARD")
UITextDef.SEASON_ALREADY_ACTIVE_BATTLE_PASS = GetL10NTextByKey("SEASON_ALREADY_ACTIVE_BATTLE_PASS")
UITextDef.SEASON_BATTLE_TIER_INVALID = GetL10NTextByKey("SEASON_BATTLE_TIER_INVALID")
UITextDef.TICKET_IS_NOT_ENOUGH = GetL10NTextByKey("TICKET_IS_NOT_ENOUGH")
UITextDef.SEASON_BATTLE_PASS_NOT_ACTIVE = GetL10NTextByKey("SEASON_BATTLE_PASS_NOT_ACTIVE")
UITextDef.FORBID_VIEW_STATS = GetL10NTextByKey("FORBID_VIEW_STATS")
UITextDef.FORBID_VIEW_HISTORY = GetL10NTextByKey("FORBID_VIEW_HISTORY")
UITextDef.SEASON_NOT_JOINED = GetL10NTextByKey("SEASON_NOT_JOINED")
UITextDef.OFF_SEASON_BATTLE_PASS = GetL10NTextByKey("OFF_SEASON_BATTLE_PASS")
UITextDef.BATTLE_TIER_LEVEL_AWARD_RECEIVED = GetL10NTextByKey("BATTLE_TIER_LEVEL_AWARD_RECEIVED")

UITextDef.CHALLENGE_NOT_EXIST = GetL10NTextByKey("CHALLENGE_NOT_EXIST")
UITextDef.CHALLENGE_WEEKLY_NOT_COMPLETED = GetL10NTextByKey("CHALLENGE_WEEKLY_NOT_COMPLETED")
UITextDef.CHALLENGE_WEEKLY_HAS_AWARDED = GetL10NTextByKey("CHALLENGE_WEEKLY_HAS_AWARDED")
UITextDef.CHALLENGE_HAS_EXPIRED = GetL10NTextByKey("CHALLENGE_HAS_EXPIRED")
UITextDef.CHALLENGE_SUB_NOT_EXIST = GetL10NTextByKey("CHALLENGE_SUB_NOT_EXIST")
UITextDef.CHALLENGE_SUB_NOT_COMPLETED = GetL10NTextByKey("CHALLENGE_SUB_NOT_COMPLETED")

UITextDef.CHAT_TEAM_INTERVAL_LIMITE = GetL10NTextByKey("CHAT_TEAM_INTERVAL_LIMITE")
UITextDef.UI_STATIC_SELFCHAT_PREFIX = GetL10NTextByKey("UI_STATIC_SELFCHAT_PREFIX")
UITextDef.CHAT_NOT_EMPTY = GetL10NTextByKey("CHAT_NOT_EMPTY")
UITextDef.CHAT_RESULT_UNKNOW = GetL10NTextByKey("CHAT_RESULT_UNKNOW")
UITextDef.CHAT_IN_COOLDOWN = GetL10NTextByKey("CHAT_IN_COOLDOWN")
UITextDef.CHAT_CONTENT_LENGTH = GetL10NTextByKey("CHAT_CONTENT_LENGTH")
UITextDef.CHAT_CHANNEL_INVALID = GetL10NTextByKey("CHAT_CHANNEL_INVALID")
UITextDef.CHAT_NO_ROOM = GetL10NTextByKey("CHAT_NO_ROOM")
UITextDef.CHAT_NO_FRIEND = GetL10NTextByKey("CHAT_NO_FRIEND")
UITextDef.CHAT_NOT_HAVE_CORPS = GetL10NTextByKey("CHAT_NOT_HAVE_CORPS")

UITextDef.PLAYER_INFO_BEST_RANK_COUNT = GetL10NTextByKey("PLAYER_INFO_BEST_RANK_COUNT")

UITextDef.UI_STATIC_CHANGEABLE_DEF = GetL10NTextByKey("UI_STATIC_CHANGEABLE_DEF")
UITextDef.UI_STATIC_CHANGEABLE_COLOR = GetL10NTextByKey("UI_STATIC_CHANGEABLE_COLOR")

UITextDef.IN_DEVELOPMENT = GetL10NTextByKey("IN_DEVELOPMENT")

UITextDef.LOBBYCHAT_VOICEMSGTEMPLATE = GetL10NTextByKey("LOBBYCHAT_VOICEMSGTEMPLATE")
UITextDef.LOBBYCHAT_TEAMINGMSGTEMPLATE = GetL10NTextByKey("LOBBYCHAT_TEAMINGMSGTEMPLATE")
UITextDef.LOBBYCHAT_TEXTMSGTEMPLATE = GetL10NTextByKey("LOBBYCHAT_TEXTMSGTEMPLATE")
UITextDef.LOBBYCHAT_FRIEND_CHANNEL = GetL10NTextByKey("LOBBYCHAT_FRIEND_CHANNEL")
UITextDef.LOBBYCHAT_WORLD_CHANNEL = GetL10NTextByKey("LOBBYCHAT_WORLD_CHANNEL")
UITextDef.LOBBYCHAT_TEAM_CHANNEL = GetL10NTextByKey("LOBBYCHAT_TEAM_CHANNEL")
UITextDef.LOBBYCHAT_ROOM_CHANNEL = GetL10NTextByKey("LOBBYCHAT_ROOM_CHANNEL")
UITextDef.LOBBYCHAT_CHAT_CORPS = GetL10NTextByKey("LOBBYCHAT_CORPS_CHANNEL")
UITextDef.LOBBYCHAT_TEAMINGMODE_TOW = GetL10NTextByKey("LOBBYCHAT_TEAMINGMODE_TOW")
UITextDef.LOBBYCHAT_TEAMINGMODE_FOUR = GetL10NTextByKey("LOBBYCHAT_TEAMINGMODE_FOUR")
UITextDef.LOBBYCHAT_TEAMINGMODE_CLASSIC = GetL10NTextByKey("LOBBYCHAT_TEAMINGMODE_CLASSIC")
UITextDef.LOBBYCHAT_SYSTEMMSGTEMPLATE = GetL10NTextByKey("LOBBYCHAT_SYSTEMMSGTEMPLATE")
UITextDef.LOBBYCHAT_SYSTEM = GetL10NTextByKey("LOBBYCHAT_SYSTEM")
UITextDef.LOBBYCHAT_TEAM_INVITE = GetL10NTextByKey("LOBBYCHAT_TEAM_INVITE")
UITextDef.STATISTIC_BASE_GAME_COUNT = GetL10NTextByKey("STATISTIC_BASE_GAME_COUNT")
UITextDef.STATISTIC_BASE_WIN_COUNT = GetL10NTextByKey("STATISTIC_BASE_WIN_COUNT")
UITextDef.STATISTIC_BASE_RANKTOP10_COUNT = GetL10NTextByKey("STATISTIC_BASE_RANKTOP10_COUNT")
UITextDef.STATISTIC_BASE_KILL_COUNT = GetL10NTextByKey("STATISTIC_BASE_KILL_COUNT")
UITextDef.STATISTIC_BASE_KILLDEAD_COUNT = GetL10NTextByKey("STATISTIC_BASE_KILLDEAD_COUNT")
UITextDef.STATISTIC_BATTLE_MAX_KILL_COUNT = GetL10NTextByKey("STATISTIC_BATTLE_MAX_KILL_COUNT")
UITextDef.STATISTIC_BATTLE_MAX_DAMAGE_COUNT = GetL10NTextByKey("STATISTIC_BATTLE_MAX_DAMAGE_COUNT")
UITextDef.STATISTIC_BATTLE_AVE_DAMAGE_RATE = GetL10NTextByKey("STATISTIC_BATTLE_AVE_DAMAGE_RATE")
UITextDef.STATISTIC_BATTLE_HIT_RATE = GetL10NTextByKey("STATISTIC_BATTLE_HIT_RATE")
UITextDef.STATISTIC_BATTLE_CRI_DAMAGE_COUNT = GetL10NTextByKey("STATISTIC_BATTLE_CRI_DAMAGE_COUNT")
UITextDef.STATISTIC_BATTLE_CRI_DAMAGE_RATE = GetL10NTextByKey("STATISTIC_BATTLE_CRI_DAMAGE_RATE")
UITextDef.STATISTIC_SURVIVAL_MAX_SURVIVAL_TIME = GetL10NTextByKey("STATISTIC_SURVIVAL_MAX_SURVIVAL_TIME")
UITextDef.STATISTIC_SURVIVAL_AVE_SURVIVAL_TIME = GetL10NTextByKey("STATISTIC_SURVIVAL_AVE_SURVIVAL_TIME")
UITextDef.STATISTIC_SURVIVAL_MAX_MOVE_DISTANCE = GetL10NTextByKey("STATISTIC_SURVIVAL_MAX_MOVE_DISTANCE")
UITextDef.STATISTIC_SURVIVAL_AVE_MOVE_DISTANCE = GetL10NTextByKey("STATISTIC_SURVIVAL_AVE_MOVE_DISTANCE")
UITextDef.STATISTIC_SURVIVAL_WIN_RATE = GetL10NTextByKey("STATISTIC_SURVIVAL_WIN_RATE")
UITextDef.STATISTIC_SURVIVAL_TOP10_RATE = GetL10NTextByKey("STATISTIC_SURVIVAL_TOP10_RATE")
UITextDef.STATISTIC_SURVIVAL_AVE_CURE = GetL10NTextByKey("STATISTIC_SURVIVAL_AVE_CURE")
UITextDef.STATISTIC_SURVIVAL_CURE_TEAM_COUNT = GetL10NTextByKey("STATISTIC_SURVIVAL_CURE_TEAM_COUNT")

UITextDef.COMMON_SINGLE_NUMBER = {
    GetL10NTextByKey("COMMON_NUMBER_1"),
    GetL10NTextByKey("COMMON_NUMBER_2"),
    GetL10NTextByKey("COMMON_NUMBER_3"),
    GetL10NTextByKey("COMMON_NUMBER_4"),
    GetL10NTextByKey("COMMON_NUMBER_5"),
    GetL10NTextByKey("COMMON_NUMBER_6"),
    GetL10NTextByKey("COMMON_NUMBER_7"),
    GetL10NTextByKey("COMMON_NUMBER_8"),
    GetL10NTextByKey("COMMON_NUMBER_9"),
    GetL10NTextByKey("COMMON_NUMBER_10")
}

UITextDef.HOMELAND_MARK_BUILDING_UPGRADE_TITLE = GetL10NTextByKey("HOMELAND_MARK_BUILDING_UPGRADE_TITLE")
UITextDef.HOMELAND_MARK_BUILDING_UPGRADE_PREREQUISITE = GetL10NTextByKey("HOMELAND_MARK_BUILDING_UPGRADE_PREREQUISITE")
UITextDef.HOMELAND_MARK_BUILDING_UPGRADE_CONFIRM = GetL10NTextByKey("HOMELAND_MARK_BUILDING_UPGRADE_CONFIRM")
UITextDef.HOMELAND_MARK_BUILDING_UPGRADE_CONFIRM_CONTENT = GetL10NTextByKey("HOMELAND_MARK_BUILDING_UPGRADE_CONFIRM_CONTENT")
UITextDef.HOMELAND_BUILDING_SIZE_FORMAT = GetL10NTextByKey("HOMELAND_BUILDING_SIZE_FORMAT")
UITextDef.HOMELAND_EXCHANGE_DESC_FORMAT = GetL10NTextByKey("HOMELAND_EXCHANGE_DESC_FORMAT")
UITextDef.UI_HOMELAND_EXCHANGE_TITLE = GetL10NTextByKey("UI_HOMELAND_EXCHANGE_TITLE")
UITextDef.UI_HOMELAND_EXCHANGE_COMMIT = GetL10NTextByKey("UI_HOMELAND_EXCHANGE_COMMIT")
UITextDef.HOMELAND_EXCHANGE_ITEM_NOT_ENOUGH_TOAST  = GetL10NTextByKey("HOMELAND_EXCHANGE_ITEM_NOT_ENOUGH_TOAST")
UITextDef.HOMELAND_MOVE_OUT_OF_BLOCK  = GetL10NTextByKey("HOMELAND_MOVE_OUT_OF_BLOCK")
UITextDef.HOMELAND_REMOVE_BUILDING_CONFIRM  = GetL10NTextByKey("HOMELAND_REMOVE_BUILDING_CONFIRM")
UITextDef.HOMELAND_REMOVE_BUILDING_CONFIRM_CONTENT  = GetL10NTextByKey("HOMELAND_REMOVE_BUILDING_CONFIRM_CONTENT")
UITextDef.HOMELAND_REMOVE_BUILDING_TITLE  = GetL10NTextByKey("HOMELAND_REMOVE_BUILDING_TITLE")
UITextDef.HOMELAND_BUY_STYLE  = GetL10NTextByKey("HOMELAND_BUY_STYLE")
UITextDef.HOMELAND_SWITCH_STYLE  = GetL10NTextByKey("HOMELAND_SWITCH_STYLE")
UITextDef.HOMELAND_STYLE_UNLOCK_CONDITION  = GetL10NTextByKey("HOMELAND_STYLE_UNLOCK_CONDITION")
UITextDef.HOMELAND_SWITCH_STYLE_DIALOG_CONTENT  = GetL10NTextByKey("HOMELAND_SWITCH_STYLE_DIALOG_CONTENT")
UITextDef.HOMELAND_RECOVER_STYLE_DIALOG_CONTENT  = GetL10NTextByKey("HOMELAND_RECOVER_STYLE_DIALOG_CONTENT")
UITextDef.HOMELAND_RECOVER_STYLE_DIALOG_NEGATIVE_BTN_TEXT  = GetL10NTextByKey("HOMELAND_RECOVER_STYLE_DIALOG_NEGATIVE_BTN_TEXT")
UITextDef.ANNOUNCEMENT_LABEL  = GetL10NTextByKey("ANNOUNCEMENT_LABEL")

UITextDef.FFA_TEAM_SURVIVE_NUM = GetL10NTextByKey("FFA_TEAM_SURVIVE_NUM")
UITextDef.READING_WATCH_MATE = GetL10NTextByKey("READING_WATCH_MATE")
UITextDef.NO_VALID_WATCH_MATE = GetL10NTextByKey("NO_VALID_WATCH_MATE")
UITextDef.FFA_WATCH_MATE_COUNTDOWN = GetL10NTextByKey("FFA_WATCH_MATE_COUNTDOWN")
UITextDef.FFA_WATCH_BATTLE_DEFAULT_TEXT = GetL10NTextByKey("FFA_WATCH_BATTLE_DEFAULT_TEXT")
UITextDef.FFA_WATCH_BATTLE_ADDITIONAL_SUCCESS = GetL10NTextByKey("FFA_WATCH_BATTLE_ADDITIONAL_SUCCESS")
UITextDef.FFA_WATCH_OTHER_TEXT = GetL10NTextByKey("FFA_WATCH_OTHER_TEXT")
UITextDef.WATCH_BATTLE_MODE = GetL10NTextByKey("WATCH_BATTLE_MODE")
UITextDef.FFA_WATCH_OTHER_COUNTDOWN = GetL10NTextByKey("FFA_WATCH_OTHER_COUNTDOWN")
UITextDef.FFA_SINGLE_WATCH_BATTLE = GetL10NTextByKey("FFA_SINGLE_WATCH_BATTLE")

UITextDef.TIMER_TEXT_BLOCK_FORMAT_FULL = {
    UISetUtils.GetTextByKey("COMMON_TIME_DAY"),
    UISetUtils.GetTextByKey("COMMON_TIME_HOUR"),
    UISetUtils.GetTextByKey("COMMON_TIME_MINUTE"),
    UISetUtils.GetTextByKey("COMMON_TIME_SECOND"),
}

UITextDef.SEVEN_DAY_HAS_AWARD  = GetL10NTextByKey("SEVEN_DAY_HAS_AWARD")
UITextDef.NPC_RESET_NOTIFY          = GetL10NTextByKey("NPC_RESET_NOTIFY")
UITextDef.NPC_RESET_NOTIFY_OVER     = GetL10NTextByKey("NPC_RESET_NOTIFY_OVER")
UITextDef.NPC_RESET_NOTIFY_CANCEL   = GetL10NTextByKey("NPC_RESET_NOTIFY_CANCEL")

UITextDef.CHAT_MESSAGE_ITEM_GRADE_FORMAT = GetL10NTextByKey("CHAT_MESSAGE_ITEM_GRADE_FORMAT")
UITextDef.ITEM_GRADE_COLOR_TEXT =
{
    [0] = GetL10NTextByKey("ITEM_GRADE_COLOR_TEXT_0"),
    [1] = GetL10NTextByKey("ITEM_GRADE_COLOR_TEXT_1"),
    [2] = GetL10NTextByKey("ITEM_GRADE_COLOR_TEXT_2"),
    [3] = GetL10NTextByKey("ITEM_GRADE_COLOR_TEXT_3"),
    [4] = GetL10NTextByKey("ITEM_GRADE_COLOR_TEXT_4"),
}
UITextDef.FFA_QUEST_RECEIVE_QUEST  = GetL10NTextByKey("FFA_QUEST_RECEIVE_QUEST")
UITextDef.FFA_QUEST_COMPLETE_QUEST = GetL10NTextByKey("FFA_QUEST_COMPLETE_QUEST")
UITextDef.SHIP_GRADE_TEXT =
{
    [0] = GetL10NTextByKey("SHIP_GRADE_TEXT_0"),
    [1] = GetL10NTextByKey("SHIP_GRADE_TEXT_1"),
    [2] = GetL10NTextByKey("SHIP_GRADE_TEXT_2"),
    [3] = GetL10NTextByKey("SHIP_GRADE_TEXT_3"),
}
UITextDef.SHIP_PROP_CATEGORY_TEXT =
{
    [1] = GetL10NTextByKey("SHIP_PROP_CATEGORY_TEXT_1"),
    [2] = GetL10NTextByKey("SHIP_PROP_CATEGORY_TEXT_2"),
    [3] = GetL10NTextByKey("SHIP_PROP_CATEGORY_TEXT_3"),
    [4] = GetL10NTextByKey("SHIP_PROP_CATEGORY_TEXT_4"),
}

UITextDef.LAYOUT_NAME =
{
    [1] = GetL10NTextByKey("SETTING_LAYOUT_STYLE_1"),
    [2] = GetL10NTextByKey("SETTING_LAYOUT_STYLE_2"),
}

UITextDef.FAILED_OBTAIN_SERVER_LIST = GetL10NTextByKey("FAILED_OBTAIN_SERVER_LIST")
UITextDef.FAILED_ENTER_LAST_DUNGEON = GetL10NTextByKey("FAILED_ENTER_LAST_DUNGEON")
UITextDef.FAILED_OBTAIN_SERVER_INFO = GetL10NTextByKey("UI_LOGIN_SERVER_ERROR")

UITextDef.COMMON_AWARD_GET = GetL10NTextByKey("COMMON_AWARD_GET")
UITextDef.COMMON_AWARD_GETED = GetL10NTextByKey("COMMON_AWARD_GETED")
UITextDef.COMMON_MULTIPLE = GetL10NTextByKey("COMMON_MULTIPLE")

UITextDef.COMMON_MIN = GetL10NTextByKey("COMMON_MIN")
UITextDef.COMMON_KM = GetL10NTextByKey("COMMON_KM")

UITextDef.DEAD_CAUSER_NAME =
{
    [-1] = GetL10NTextByKey("COMMON_DEAD_CAUSER_NAME_DROP"),            --跌落
    [-2] = GetL10NTextByKey("COMMON_DEAD_CAUSER_NAME_DROWN"),           --溺水
    [-3] = GetL10NTextByKey("COMMON_DEAD_CAUSER_NAME_DYING_REDUCE"),    --重伤自然衰减
    [-4] = GetL10NTextByKey("COMMON_DEAD_CAUSER_NAME_POISON"),          --毒圈
}

UITextDef.DEAD_DAMAGE_NAME =
{
    [101] = GetL10NTextByKey("COMMON_DEAD_CAUSER_NAME_POISON"),             --毒圈
    [102] = GetL10NTextByKey("COMMON_DEAD_CAUSER_NAME_DROP"),               --跌落
    [103] = GetL10NTextByKey("COMMON_DEAD_CAUSER_NAME_DYING_REDUCE"),       --重伤自然衰减
    [104] = GetL10NTextByKey("COMMON_DEAD_CAUSER_NAME_KILL_SELF"),          --自杀伤害
    [105] = GetL10NTextByKey("COMMON_DEAD_CAUSER_NAME_DROWN"),              --溺水伤害
    [209] = GetL10NTextByKey("COMMON_DEAD_DAMAGE_NAME_SHIP_EMBOLON"),       --船冲撞
    [251] = GetL10NTextByKey("COMMON_DEAD_DAMAGE_NAME_SHIP_FIRING"),        --船燃烧
    [252] = GetL10NTextByKey("COMMON_DEAD_DAMAGE_NAME_SHIP_LEAKING"),       --船漏水
    [253] = GetL10NTextByKey("COMMON_DEAD_DAMAGE_NAME_SHIP_BUMPING"),       --船撞死游泳人
    [301] = GetL10NTextByKey("COMMON_DEAD_DAMAGE_NAME_HUMAN_EMPTY_HAND"),   --人空手伤害
}

UITextDef.DISPLAY_ITEM_CATEGORY =
{
    [ItemCategoryDef.SHIP] = GetL10NTextByKey("UI_DISPLAY_SHIP"),
    [ItemCategoryDef.SHIP_SKIN] = GetL10NTextByKey("UI_DISPLAY_SHIP_SKIN"),
    [ItemCategoryDef.FASHION] = GetL10NTextByKey("UI_DISPLAY_FASHION")
}


UITextDef.ANTIADDICTION_ERRORCODE = {
	[101] = GetL10NTextByKey("ANTIADDICTION_NO_AUTHENTICATION"),
	[102] = GetL10NTextByKey("ANTIADDICTION_TOURISTS_TIMEOUT"),
	[103] = GetL10NTextByKey("ANTIADDICTION_SAMEDEVICE_TOURIST_REPEAT"),
	[104] = GetL10NTextByKey("ANTIADDICTION_JUVENILES_INVALID_TIME"),
	[105] = GetL10NTextByKey("ANTIADDICTION_JUVENILES_TIMEOUT_HOLIDAYS"),
	[106] = GetL10NTextByKey("ANTIADDICTION_JUVENILES_TIMEOUT_NORMAL")
}

UITextDef.USER_BANNED_INGAME = GetL10NTextByKey("USER_BANNED_INGAME")
UITextDef.USER_BANNED_LOGIN = GetL10NTextByKey("USER_BANNED_LOGIN")
UITextDef.USER_BANNED_LOGIN_FOREVER = GetL10NTextByKey("USER_BANNED_LOGIN_FOREVER")
UITextDef.LOGIN_RESPONSE_NOTFOUND = GetL10NTextByKey("LOGIN_RESPONSE_NOTFOUND")
UITextDef.ANTIADDICTION_TICKOUT = GetL10NTextByKey("ANTIADDICTION_TICKOUT")
UITextDef.ACTIVATION_CODE_INVALID = GetL10NTextByKey("ACTIVATION_CODE_INVALID")
UITextDef.ACTIVATION_CODE_ALREADYUSED = GetL10NTextByKey("ACTIVATION_CODE_ALREADYUSED")
UITextDef.ACTIVATION_CODE_OVERTIME = GetL10NTextByKey("ACTIVATION_CODE_OVERTIME")


local FashionSlotCategory = HumanAvatarDef.FashionSlotCategory

UITextDef.LOBBY_CAPTAIN_FITTING =
{
    [FashionSlotCategory.Hat]   = GetL10NTextByKey("UI_STATIC_LOBBY_CAPTAIN_HEAD_FITTING"),
    [FashionSlotCategory.Upper] = GetL10NTextByKey("UI_STATIC_LOBBY_CAPTAIN_UPPER_FITTING"),
    [FashionSlotCategory.Lower] = GetL10NTextByKey("UI_STATIC_LOBBY_CAPTAIN_LOWER_FITTING"),
    [FashionSlotCategory.Shoe]  = GetL10NTextByKey("UI_STATIC_LOBBY_CAPTAIN_SHOE_FITTING"),
}


UITextDef.LOBBY_CAPTAIN_WEAPON_FITTING = GetL10NTextByKey("UI_STATIC_LOBBY_CAPTAIN_WEAPON_FITTING")
UITextDef.LOBBY_CAPTAIN_CLASSIC_PREFIX = GetL10NTextByKey("UI_STATIC_LOBBY_CAPTAIN_CLASSIC_PREFIX")

UITextDef.LOBBY_CAPTAIN_AVATAR_DYNAMIC_SLOT =
{
    [FashionSlotCategory.Hat]   = GetL10NTextByKey("UI_STATIC_LOBBY_CAPTAIN_AVATAR_DYNAMIC_HAT"),
    [FashionSlotCategory.Upper] = GetL10NTextByKey("UI_STATIC_LOBBY_CAPTAIN_AVATAR_DYNAMIC_UPPER"),
    [FashionSlotCategory.Lower] = GetL10NTextByKey("UI_STATIC_LOBBY_CAPTAIN_AVATAR_DYNAMIC_LOWER"),
    [FashionSlotCategory.Shoe]  = GetL10NTextByKey("UI_STATIC_LOBBY_CAPTAIN_AVATAR_DYNAMIC_SHOE"),
}

local FashionType = HumanAvatarDef.FashionType

UITextDef.FASHION_ARMOR_NAME =
{
    [FashionType.Basic]  = GetL10NTextByKey("UI_STATIC_ARMOR_BASIC"),
    [FashionType.Knight]  = GetL10NTextByKey("UI_STATIC_ARMOR_KNIGHT"),
    [FashionType.Robe]    = GetL10NTextByKey("UI_STATIC_ARMOR_ROBE"),
    [FashionType.Stealth] = GetL10NTextByKey("UI_STATIC_ARMOR_STEALTH"),
    [FashionType.Light]   = GetL10NTextByKey("UI_STATIC_ARMOR_LIGHT"),
}

UITextDef.UI_CAPTAIN_PREVIEW = GetL10NTextByKey("UI_CAPTAIN_PREVIEW")
UITextDef.FRIEND_ALREADY_SEND_TODY = GetL10NTextByKey("FRIEND_ALREADY_SEND_TODY")
UITextDef.FRIEND_SEND_GIFT_LIMIT = GetL10NTextByKey("FRIEND_SEND_GIFT_LIMIT")
UITextDef.FRIEND_RELATION_COUNT_LIMIT = GetL10NTextByKey("FRIEND_RELATION_COUNT_LIMIT")

UITextDef.FRIEND_RELATION_MAX_COUNT = GetL10NTextByKey("FRIEND_RELATION_MAX_COUNT")
UITextDef.RELATION_COLOR_KEY =
{
    [1] = GetL10NTextByKey("UI_RELATION_COLOR_1"),
    [2] = GetL10NTextByKey("UI_RELATION_COLOR_2"),
    [3] = GetL10NTextByKey("UI_RELATION_COLOR_3"),
    [4] = GetL10NTextByKey("UI_RELATION_COLOR_4"),
}

UITextDef.FRIEND_CREATE_RELATION_FAIL = GetL10NTextByKey("FRIEND_CREATE_RELATION_FAIL")
UITextDef.FRIEND_SEND_GIFT_FAIL = GetL10NTextByKey("FRIEND_SEND_GIFT_FAIL")
UITextDef.FRIEND_APPLY_RELATION_FAIL = GetL10NTextByKey("FRIEND_APPLY_RELATION_FAIL")
UITextDef.FRIEND_SET_PRIORITY_FAIL = GetL10NTextByKey("FRIEND_SET_PRIORITY_FAIL")
UITextDef.FRIEND_CANCEL_RELATION_FAIL = GetL10NTextByKey("FRIEND_CANCEL_RELATION_FAIL")
UITextDef.FRIEND_APPLY_CANCEL_RELATION_FAIL = GetL10NTextByKey("FRIEND_APPLY_CANCEL_RELATION_FAIL")
UITextDef.FRIEND_SEND_RESERVATION_FAIL = GetL10NTextByKey("FRIEND_SEND_RESERVATION_FAIL")
UITextDef.FRIEND_RESERVATION_NO_REPLY = GetL10NTextByKey("FRIEND_RESERVATION_NO_REPLY")
UITextDef.FRIEND_ACCEPT_RESERVATION_FAIL = GetL10NTextByKey("FRIEND_ACCEPT_RESERVATION_FAIL")
UITextDef.FRIEND_SEND_COIN_SUCCESS = GetL10NTextByKey("FRIEND_SEND_COIN_SUCCESS")


UITextDef.UI_BASIC_LEVEL = GetL10NTextByKey("UI_BASIC_LEVEL")

UITextDef.BASIC_FASHION_DESC = GetL10NTextByKey("BASIC_FASHION_DESC")
UITextDef.LOBBY_ITEM_USE_INTIMACY_MAX = GetL10NTextByKey("LOBBY_ITEM_USE_INTIMACY_MAX")

UITextDef.UI_STATIC_LOBBY_SHIP_DETAIL_BASIC_INFO = GetL10NTextByKey("UI_STATIC_LOBBY_SHIP_DETAIL_BASIC_INFO")
UITextDef.UI_STATIC_LOBBY_SHIP_DETAIL_DETAILED_INFO = GetL10NTextByKey("UI_STATIC_LOBBY_SHIP_DETAIL_DETAILED_INFO")

UITextDef.LOBBY_NET_WORK_WEAKNESS = GetL10NTextByKey("LOBBY_NET_WORK_WEAKNESS")

UITextDef.UI_STATIC_LOBBY_CAPTAIN_HUMAN_FASHION = GetL10NTextByKey("UI_STATIC_LOBBY_CAPTAIN_HUMAN_FASHION")
UITextDef.UI_STATIC_LOBBY_CAPTAIN_WEAPON_FASHION = GetL10NTextByKey("UI_STATIC_LOBBY_CAPTAIN_WEAPON_FASHION")

UITextDef.UI_STATIC_LOBBY_CAPTAIN_VISUAL = GetL10NTextByKey("UI_STATIC_LOBBY_CAPTAIN_VISUAL")
UITextDef.UI_STATIC_LOBBY_CAPTAIN_DECORATION = GetL10NTextByKey("UI_STATIC_LOBBY_CAPTAIN_DECORATION")

UITextDef.LOBBY_DECORATION_EQUIP_SAME = GetL10NTextByKey("LOBBY_DECORATION_EQUIP_SAME")
UITextDef.LOBBY_DECORATION_NOT_EQUIP = GetL10NTextByKey("LOBBY_DECORATION_NOT_EQUIP")
UITextDef.LOBBY_DECORATION_NOT_FOUND = GetL10NTextByKey("LOBBY_DECORATION_NOT_FOUND")

UITextDef.L10N_YMDTIME_FORMAT2 = GetL10NTextByKey("L10N_YMDTIME_FORMAT2")
UITextDef.L10N_YMDTIME_FORMAT3 = GetL10NTextByKey("L10N_YMDTIME_FORMAT3")
UITextDef.LOBBY_SHOP_SUIT_TITLE = GetL10NTextByKey("LOBBY_SHOP_SUIT_TITLE")

UITextDef.LOBBY_CAPTAIN_HINT_WEAR_SUIT = GetL10NTextByKey("LOBBY_CAPTAIN_HINT_WEAR_SUIT")
UITextDef.LOBBY_CAPTAIN_HINT_WORD_WITH_COMMA = GetL10NTextByKey("LOBBY_CAPTAIN_HINT_WORD_WITH_COMMA")
-- UITextDef.LOBBY_CAPTAIN_HINT_WORD_WITHOUT_COMMA = GetL10NTextByKey("LOBBY_CAPTAIN_HINT_WORD_WITHOUT_COMMA")
UITextDef.LOBBY_CAPTAIN_HINT_BE_OVERLAY = GetL10NTextByKey("LOBBY_CAPTAIN_HINT_BE_OVERLAY")
UITextDef.LOBBY_CAPTAIN_HINT_TO_OVERLAY = GetL10NTextByKey("LOBBY_CAPTAIN_HINT_TO_OVERLAY")
UITextDef.LOBBY_CAPTAIN_HINT_FITTING = GetL10NTextByKey("LOBBY_CAPTAIN_HINT_FITTING")
UITextDef.LOBBY_CAPTAIN_HINT_USING_BASIC = GetL10NTextByKey("LOBBY_CAPTAIN_HINT_USING_BASIC")
UITextDef.LOBBY_CAPTAIN_HINT_THREE_ITEMS = GetL10NTextByKey("LOBBY_CAPTAIN_HINT_THREE_ITEMS")
UITextDef.LOBBY_CAPTAIN_HINT_FOUR_ITEMS = GetL10NTextByKey("LOBBY_CAPTAIN_HINT_FOUR_ITEMS")
UITextDef.LOBBY_CAPTAIN_HINT_BASIC_AFFECT_ARMOR = GetL10NTextByKey("LOBBY_CAPTAIN_HINT_BASIC_AFFECT_ARMOR")

return UITextDef