-- luacheck: ignore

-- Use Lua 5.3 standard libraries
std = "lua53"

ignore = {
    "6..",      -- Ignore Formatting issues (6xx)
    "21./_.*",  -- Ignore unused warnings (21x) if variable is prefixed with underscore
    "212",      -- Ignore unused argument
    "311",      -- Ignore value assigned to a local variable is unused.
    "213",      -- Ignore unused loop variable.
}

-- Warn on global table access unless otherwise
not_globals = { "_G" }

-- Read-and-Write global variables
globals = {
}

-- Read-Only global variables
read_globals = {
    "_G",

    -- standard lua lib
    "coroutine",
    "debug",
    "io",
    "math",
    "os",
    "package",
    "string",
    "table",
    "utf8",

    -- C global variables
    "GWorld",
    "GShippingBuild",
    "GWithEditor",
    "GPlayInCommandlet",
    "GLaunchParams",
    "GLuaEditorHelper",
    "GPlayInEditor",
    "GEnableNewLua",
    "GIsDedicatedServer",
    "GDefaultTolerance",

    -- C global functions
    "printScreen",
    "spawnactor",
    "class",
    "log",
    "logwarning",
    "logerror",
    "logdebug",
    "logevent",
    "getcontentdir",
    "luaholder",
    "exposetable",
    "taketableref",
    "uetype",
    "file_exists",
    "getfilestring",
    "getabsolutefilestring",
    "getdirfilepaths",
    "setLuaErrorCallback",
    "printrefobjects",
    "luagc",
    "requirewithfullpath",
    "setenabledebuglog",
    "getseconds",
    "getframebegintime",
    "load",
    "dynamic_require",
    "msgtoluatable",
    "setrandomseed",
    "getrandomintegerinrange",
    "printLuaDebuginfo",
    "sethooklogenabled",
    "sethandlecounttogc",
    "rts",
    "rte",
    "createtask",
    "destroytask",
    "flushtask",
    "isvalidhandle",
    "enumtoint",
    "isInteger",
    "packtowrapper",
    "unpackfromwrapper",
    "createDelegate",
    "bindDelegate",
    "unbindDelegate",
    "callDelegate",
    "testemptyfunction",
    "cacheallpropertyandfunctions",
    "statbegin",
    "statend",
    "vector",
    "vector2d",
    "setRequireCheckKeys",
    "printRequireCheckResult",
    "printMemoryUsage",
    "printPluginMemory",
    "destroyUserData",
    "getWorld",

    -- Lua global funcitons
    "getdebuginfo_f",
    "t2s",
    "getdebuginfo_l",

    -- C++ classes
    "ShipExporter",
    "EngineExtShell",
    "EngineExtActorShell",
    "CommonShell",
    "CommonActorShell",
    "ClientShell",
    "GameActorShell",
    "GameDungeonShell",
    "GameCameraShotShell",
    "GameObjectShell",
    "GameSoundShell",
    "ServerShell",
    "DungeonShell",
    "EngineExtSetting",
    "InputManager",
    "UpdateProcedure",
    "HotUpdateProcedure",
    "HotUpdateDLCProcedure",
    "FileDownloader",
    "UIMapCoord",
    "UIMapMove",
    "UIMapNav",
    "Image",
    "WrapBox",
    "TextBlock",
    "KMRichTextBlock",
    "UIMapOpPointWithActor",
    "UIMapOpOrientationWithActor",
    "UIMapCameraFov",
    "UIMapOpStaticPath",
    "PiratesUserWidget",
    "Border",
    "OceanSystem",
    "ShipPartForDamage",
    "CustomReplicationComponent",
    "LuaCustomDataWrapper",
    "U4LDelegateProxy",
    "UIMapOpPoisonCircle",
    "UIMapOpFlagPointLine",
    "UIMapOpCompass",
    "UIMapOpSafeCirclePath",
    "SphereComponent",
    "ChangeTargetInfo",
    "HandleMoveInfo",
    "OffsetMoveInfo",
    "CameraShakeInfo",
    "UIMapOpFFATeamMember",
    "FovInfo",
    "MoveArmLenInfo",
    "UIMapOpFFATeamMemberHead",
    "SyncArmRotInfo",
    "ArmRotInfo",
    "CameraTrackInfo",
    "AISense_Damage",
    "UIMapScale",
    "UIMapOpPoint",
    "GameTestAutomationDelegate",
    "AISense_Hearing",
    "ChildActorComponent",
    "AIDoorExporter",
    "LowEntryExtendedStandardLibrary",
    "FileDownloaderBPLibrary",
    "BlueprintPathsLibrary",
    "BlueprintFileUtilsBPLibrary",
    "AIVehicleExporter",

    -- C++ enums
    "EAudioComponentPlayState",
    "ENetworkFailure",
    "ECollisionEnabled",
    "EShipImpactArea",
    "EShipPosture",
    "EShipGear",
    "EShipNetRole",
    "ESlateVisibility",
    "EAudioFaderCurve",
    "EMapNavGridPathFollowingResult",
    "EPathFollowingResult",
    "EPathFollowingRequestResult",
    "EAnimationMode",
    "EAttachLocation",
    "EUMGSequencePlayMode",
    "EViewTargetBlendFunction",
    "EMontagePlayReturnType",
    "ECameraProjectionMode",
    "EGameActorMoveMode",
    "EUpdateReturnCode",
    "EQuitPreference",
    "EMapShape",
    "EMinTimeUnit",
    "EInputKey",
    "EGestureType",
    "ECheckBoxState",
    "EShipSailState",
    "EHorizontalAlignment",
    "ETextJustify",
    "EHorizontalAlignment",
    "EVerticalAlignment",
    "EBlendMode",
    "ECrashType",
    "ESlateBrushMirrorType",
    "EShipMoveGearBuffType",
    "EAttachmentRule",
    "EPropertyOverlapType",
    "ECameraAnimPlaySpace",
    "EEasingFunc",
    "EPiratesGameStatus",
    "ECollisionChannel",
    "EDrawDebugTrace",
    "EReplicatedCustomPropertyType",
    "EPiratesGridRegionType",
    "ECollisionResponse",
    "EMovementMode",
    "EDynamicReplicationPropertyType",
    "ECustomReplicatedPropertyType",
    "ELifetimeCondition",
    "EPSCPoolMethod",
    "ECameraModeType",
    "ECameraFollowType",
    "EHandleInputType",
    "EWidgetSpace",
	"EDetachmentRule",
    "EPhysBodyOp",
    "ESlateBrushDrawType",
    "EGameNetState",
    "GVoiceViceMode",
    "EDescendantScrollDestination",
    "EComponentMobility",
    "ENetRole",

    -- BP enums
    "ENUM_AnimState",
    "ENUM_ArtTargetType",
    "Enum_BuffTimeRefreshType",
    "Enum_CameraAnim",
    "Enum_CameraType",
    "Enum_Camp",
    "Enum_DamageType",
    "Enum_EventDialogType",
    "Enum_HandlerMode",
    "Enum_HitEffectType",
    "Enum_HubGather",
    "Enum_HubVisibility",
    "Enum_ISpotType",
    "Enum_LandGather",
    "Enum_LauncherPrototype",
    "Enum_LauncherType",
    "Enum_MissionType",
    "ENUM_NPC_AI_TYPE",
    "ENUM_NpcPropertyType",
    "Enum_ShipNetRole",
    "ENUM_ShipPropertyType",
    "Enum_ShipType",
    "Enum_SkillRangeType",
    "Enum_TriggerScaleType",
    "Enum_UpdateWarn",
    "Enum_ShipWeaponSlot",
    "Enum_CameraMoveType",
    "Enum_HumanWeaponType",
    "Enum_HumanWeaponPostion",
    "Enum_HumanWeaponState",
    "Enum_HumanMovementState",
    "Enum_ExplosiveType",
    "ENUM_BotGameStage",
    "Enum_SoundType",
    "Enum_ThrowTrojectory",
    "Enum_ParachutingNewCameraStep",
    "Enum_SoundEventNotifyType",
    "ENUM_HumanGender",

    -- C++ structs
    "Vector",
    "Vector2D",
    "Rotator",
    "HumanMovementConfig",
    "HumanFallConfig",
    "ShellHumanSynMovementData",
    "ShipGearData",
    "ShipPathMoveGearConfig",
    "ShipMovementConfig",
    "ShellShipSynMovementData",
    "Transform",
    "OceanAreaPortData",
    "OceanAreaTeleportPointData",
    "ShellShipGearBuff",
    "SlateColor",
    "LinearColor",
    "SlateBrush",
    "SlateChildSize",
    "Margin",
    "Anchors",
    "MovieSceneSequencePlaybackSettings",
    "LevelSequencePlayer",
    "Box2D",
    "DynamicReplicationPropertyDefine",
    "CustomReplicationPropertyDefine",
    "InitCameraInfo",
    "HumanMountFallConfig",

    -- C++ class
    "Actor",
    "Pawn",
    "ShipPartForDamage",
    "ParticleSystemComponent",
    "DynamicReplicationGeneratedClass",
    "StaticMeshActor",

    -- C++ function libaries
    "GameplayStatics",
    "PaperSpriteBlueprintLibrary",
    "TileMapBlueprintLibrary",
    "ComposureBlueprintLibrary",
    "LensDistortionBlueprintLibrary",
    "BlueprintMaterialTextureNodesBPLibrary",
    "ControlRigLibrary",
    "RawInputFunctionLibrary",
    "StructBoxLibrary",
    "NiagaraFunctionLibrary",
    "AchievementBlueprintLibrary",
    "LeaderboardBlueprintLibrary",
    "TurnBasedBlueprintLibrary",
    "AndroidPermissionFunctionLibrary",
    "AppleARKitBlueprintLibrary",
    "AbilitySystemBlueprintLibrary",
    "GoogleARCoreSessionFunctionLibrary",
    "GoogleARCoreFrameFunctionLibrary",
    "GoogleVRControllerFunctionLibrary",
    "GoogleVRHMDFunctionLibrary",
    "GoogleVRTransition2DBPLibrary",
    "MIDIDeviceManager",
    "MixedRealityUtilLibrary",
    "MobilePatchingLibrary",
    "OculusFunctionLibrary",
    "KismetProceduralMeshLibrary",
    "SoundUtilitiesBPFunctionLibrary",
    "SoundVisualizationStatics",
    "SteamVRFunctionLibrary",
    "SteamVRControllerLibrary",
    "EditorTestsUtilityLibrary",
    "FunctionalTestingManager",
    "FunctionalTestUtilityLibrary",
    "AutomationBlueprintFunctionLibrary",
    "AnimationBlueprintLibrary",
    "MaterialEditingLibrary",
    "SequenceRecorderBlueprintLibrary",
    "BTFunctionLibrary",
    "AIBlueprintHelperLibrary",
    "KismetAnimationLibrary",
    "AudioMixerBlueprintLibrary",
    "ARBlueprintFunctionLibrary",
    "DebugDrawService",
    "BlueprintMapLibrary",
    "BlueprintPlatformLibrary",
    "BlueprintSetLibrary",
    "DataTableFunctionLibrary",
    "ImportanceSamplingLibrary",
    "KismetArrayLibrary",
    "KismetGuidLibrary",
    "KismetInputLibrary",
    "KismetInternationalizationLibrary",
    "KismetMaterialLibrary",
    "KismetMathLibrary",
    "KismetNodeHelperLibrary",
    "KismetRenderingLibrary",
    "KismetStringLibrary",
    "KismetStringTableLibrary",
    "KismetSystemLibrary",
    "KismetTextLibrary",
    "StereoLayerFunctionLibrary",
    "MeshVertexPainterKismetLibrary",
    "VisualLoggerKismetLibrary",
    "FoliageStatistics",
    "BlueprintGameplayTagLibrary",
    "HeadMountedDisplayFunctionLibrary",
    "MotionTrackedDeviceFunctionLibrary",
    "MediaBlueprintFunctionLibrary",
    "RuntimeAssetCacheBPHooks",
    "SlateBlueprintLibrary",
    "WidgetBlueprintLibrary",
    "WidgetLayoutLibrary",
    "BuglyCrashReportBPLibrary",
    "FilesFunctionLibrary",
    "PakFunctionLibrary",
    "HotUpdateDLCFunctionLibrary",
    "VersionInfoFunctionLibrary",
    "KMUMGAnimationLibrary",
    "KMUMGLibrary",
    "LogCatcher",
    "AIExtendBlueprintFunctions",
    "ExtendBlueprintFunctions",
    "GameplayExtensions",
    "RenderExtendBlueprintFunctions",
    "EditorExtendFunctions",
    "PropertyWrapperFunctionLibrary",
    "ExtendBlueprintFunctions",
    "PatchSettings",
    "GamePlatformMiscLibrary",
    "KMInstancedSceneItemActor",
    "PiratesReplicationBPHelpers",
    "UrlSettings",
    "LevelEditorPlaySettings",
    "GPerfShell",
}

local function ImportExtendedCheck(szCheckFile)
    package.preload[szCheckFile] = nil
    package.loaded[szCheckFile] = nil
    local luacheck_func = require(szCheckFile)
    for _, v in pairs(luacheck_func) do
        table.insert(read_globals, v)
    end

end

ImportExtendedCheck("luacheck_func")
